### ISSUE TITLE
Point reporting app to use the aggregator-aggregated database instead of rating-rated usage database

### ISSUE THREAD

**Issue by KRuelY** [cloudfoundry-incubator/cf-abacus#102]
Hi,

My team was discussing if there is a way to configure the reporting app to use the aggregator-aggregated database instead of rating-rated usage database. The idea is to disable rating functionality because we would like to enable it only to those who want to use rating.

I notice that aggregator has an api that will give us aggregated data without rating, but we would also like to use the graphQL that exists in the rating-app and to easily enable rating by changing a config / environment variable.

Thanks!

**Comment by jsdelfino** [comment]
Rating is effectively a no-op if you don't configure any rating function, price or charge functions (the costs and charges will just be zeroes).

You still need to include and run the rating app for now though, and I don't think that the reporting service will work if you tweak it to point it to the aggregated usage database.

We could discuss an enhancement to either make the current reporting service work off both the rated usage and the aggregated (un-rated) usage databases, or create another reporting service that would work off the aggregated usage database, but that would require quite a bit of work.

Another thing to think about is that at some point we'll probably also enable rating of individual usage (at the resource instance level) so since that step will come before usage accumulation and aggregation, when we do that then even the accumulated and aggregated usage databases will have gone through some rating step (even if again that rating can be made to be just a no-op to only produce zeroes).

**Comment by jsdelfino** [comment]
Not planning to do this unless people feel that it's really important. Closing for now, please reopen if needed.
