### ISSUE TITLE
The rate and aggregator apps running out of memory

### ISSUE THREAD

**Issue by piotrprzybylski** [cloudfoundry-incubator/cf-abacus#138]
While processing about 10000 runtime submission (100 x 100) of period of 24 hours, the ```abacus-usage-rate``` and ```abacus-usage-aggregator``` applications run out of memory.  The relevant CF events are below, there is a single instance of each application configured with 2GB of memory.

```
time                          event                 actor                     description   
2015-10-29T03:29:06.00-0700   app.crash             abacus-usage-aggregator   index: 0, reason: CRASHED, exit_description: out of memory, exit_status: 255   
2015-10-28T15:43:12.00-0700   audit.app.update      piotrp@us.ibm.com         state: STARTED   

time                          event                 actor               description   
2015-10-29T13:09:45.00-0700   app.crash             abacus-usage-rate   index: 0, reason: CRASHED, exit_description: app instance exited, exit_status: 1   
2015-10-29T03:43:52.00-0700   app.crash             abacus-usage-rate   index: 0, reason: CRASHED, exit_description: app instance exited, exit_status: 255   
2015-10-28T15:43:17.00-0700   audit.app.update      piotrp@us.ibm.com   state: STARTED   
```

**Comment by BetaFood** [comment]
Are all 10000 submissions all at one time, or are they evenly distributed across that 24 hour period? 

I've tried some tests such as running the aggregator integration test to submit 20k records in quick succession which did cause a spike in memory up to that 2GB amount due to the number of requests that it was handling.

Throttling the requests done to 100 from 1000 certainly lowered the amount of memory used. After 0dd4681e7680e36dc706ff6b66d5f920e2b04d02, the memory amount was lowered to about half with the default throttling.

On the other hand, running a test that sent about 1000 records through the whole system about every 5 minutes gave me relatively stable memory usage across all apps.

Are the issues still persistent even after the commit I mentioned above? It might also help to throttle the amount of requests as suggested in #139

**Comment by jsdelfino** [comment]
@BetaFood, @piotrprzybylski What's the status of this issue? Looks like there's no evidence of a memory leak. Are we still seeing high memory usage growth causing crashes? or is this now resolved with the changes in 0dd4681.

**Comment by jsdelfino** [comment]
@BetaFood, @piotrprzybylski What is the status of this issue? Can it be closed now?

**Comment by BetaFood** [comment]
Since we don't have any new reports, I'll be closing the issue for now.
@piotrprzybylski If you run into issues again, please feel free to reopen the issue.
