### ISSUE TITLE
Abacus Report is unable to gather the report for (end-of-month - 1) millisecond

### ISSUE THREAD

**Issue by AzureEnigma** [cloudfoundry-incubator/cf-abacus#148]
When using the link http://abacus-usage-reporting.xxx/v1/metering/organizations/:org-id/aggregated/usage/:time

We use this link to grab the usage from the end of the month. We take the time of the month the deduct one millisecond from it to get the report for that month. We submitted reports were processed on Date Tue, 03 Nov 2015 00:53:45 GMT. We tried to grab the report using:

```
http://abacus-usage-reporting.xxx/v1/metering/organizations/org-id/aggregated/usage/1448927999999
```

However, this will give us the issue
```
{
  "error": "Forbidden by design doc validate_doc_update function"
}
```

We were able to resolve this by decreasing the time ANOTHER millisecond so the query looked like this:

```
http://abacus-usage-reporting.xxx/v1/metering/organizations/org-id/aggregated/usage/1448927999998
```

**Comment by BetaFood** [comment]
The error message returned is when PouchDB gives from an error in the validate_doc_update function, I believe. Does your database have any design documents? These could be failing validation. Although in the case of the report, no document should be written back to the db, which is the strange part.

I've tried running my own tests. I ran a simple test of running the demo and querying for that organization using the timestamp of 1448927999999, but it was able to return. I've tried both with the in-memory database and a local installation of couchdb. With the local couchdb installation, I put a design document with a validate_doc_update function that always throws an error after running the demo(so nothing else can be written to the db), but in both cases, they were able to return with the (end-of-month -1) millisecond timestamp.

Do you by chance have any logs of perhaps the dbclient/dbserver or more details on what you ran when this behavior popped up?

**Comment by BetaFood** [comment]
After revisiting this, this does pop up in the case of using an api key rather than the account credentials to access a cloudant db.

In the report, the t passed by the user to the query is incremented by 1. This was to catch the case in which the user knows the exact time of the submission and queries based on that time. This would return that latest submission. The issue with the +1 is that it can go onto the next month.

The better idea is to append highest-sorted character in the collation sequence for strings. In the case of couchdb, that would be 'Z' as specified here:
http://wiki.apache.org/couchdb/View_collation#Collation_Specification
