### ISSUE TITLE
Random failures in accumulator unit test

### ISSUE THREAD

**Issue by jsdelfino** [cloudfoundry-incubator/cf-abacus#155]
As shown in this build's error log:
https://travis-ci.org/cloudfoundry-incubator/cf-abacus/jobs/89682019

**Comment by BetaFood** [comment]
The posts to aggregator that trigger the postspy are being batched as seen in the log of this build. https://s3.amazonaws.com/archive.travis-ci.org/jobs/90171357/log.txt
The test currently expects every request to call the postspy, but since more than one are batched together on occasion, the test fails.
The test needs to be fixed to accommodate for these batched calls.
