### ISSUE TITLE
Abacus-cfpack will only package the application if the package name is cf-abacus

### ISSUE THREAD

**Issue by AzureEnigma** [cloudfoundry-incubator/cf-abacus#173]
```
if(JSON.parse(fs.readFileSync(
      path.resolve(dir, 'package.json')).toString()).name === 'cf-abacus')
      return dir;
return rootDir(path.resolve(dir, '..'));
  }
```
Since abacus-cfpack is looking for the name cf-abacus in the package, you cannot use it in any other project currently.

**Comment by BetaFood** [comment]
There is the -r option that takes in a root directory which should bypass the cf-abacus check. Just make sure you don't make the mistake I did in terms of actually passing in the option when testing this out, since it slightly differs depending on whether you're running cfpack directly or through npm run. That could be a possibility if you've tried the argument before with no result.

If you're running cfpack through npm run, then:
```
npm run cfpack -- -r /path/to/your/module
```
If you're running cfpack directly through the commandline:
```
cfpack -r /path/to/your/module
```

Does that work out for you?

**Comment by AzureEnigma** [comment]
Yes, this does work out for me. Sorry for the confusion.
