### ISSUE TITLE
Build from pull request is failing.

### ISSUE THREAD

**Issue by KRuelY** [cloudfoundry-incubator/cf-abacus#199]
It seems that the build from pull request is failing because target environment is not set properly, or is not allowed to be set due to security measure from travis.

This is the error I got when travis is performing cftest:
'Error performing request: Get https://api./v2/info: dial tcp: lookup api. on 8.8.8.8:53: no such host'

It's missing the target domain after the https://api.

**Comment by BetaFood** [comment]
Since the last environment(cftest) curently depends on environment variables set in travis, pull requests will fail that test due to not having access to those defined environment variables as stated here https://docs.travis-ci.com/user/pull-requests

The cftest may need to be redone in a way such that it doesn't depend on the environment variables.

**Comment by jsdelfino** [comment]
OK we'll need to think about what we do here, as:
- Some of these env variables are private by design as they're allowing deployment of the Abacus apps to my Bluemix account;
- I'm not sure I want to allow any pull request to deploy any code (e.g. malicious modifications of the Abacus apps code) to that Bluemix account;
- If the creator of a pull request owns a separate Bluemix account (or another hosted CF-based Cloud account) that can be used to deploy the contents of the pull request, an option would be for the pull request to also configure the necessary env variables to point to that separate Cloud account.
