### ISSUE TITLE
Demo and CF bridge itest fail

### ISSUE THREAD

**Issue by jsdelfino** [cloudfoundry-incubator/cf-abacus#223]
See errors in this build: https://travis-ci.org/cloudfoundry-incubator/cf-abacus/jobs/106388556

I'm wondering if this is a timing issue, a bug caused by the usage start/end times used the test, or a bug in the computation of the time windows, as the test fails in my local build environment as well, but works if I change my machine's clock back to 01/29/2016 for example.

**Comment by hsiliev** [comment]
Might be the `isWithinWindow` function:
https://github.com/cloudfoundry-incubator/cf-abacus/blob/d2794805b29fad0b3fe820b23e69518bcb43bfca/test/cf/bridge/src/test/test.js#L42-L43

**Comment by jsdelfino** [comment]
The demo seems to be failing too, so that's not just this itest, looks like a bigger problem in the reporting service. Ben and I are investigating.

**Comment by BetaFood** [comment]
This issue affects the report in general.
This is an issue that only pops up on the 2nd of the month for the report. Since the report does a descending order, the bounds from a default setup would be something along the lines of [ X, X - 1 ].
The code for calculating the bounds was always adding + 1 to the second bound here which would result in making a range of [ X, X] which gives an empty range.

35020a2771e060e9a8387f1e8008f5f220783c6c should fix this error.

**Comment by jsdelfino** [comment]
Looks like that fixed it.
