### ISSUE TITLE
Abacus cannot deal with out of order submission

### ISSUE THREAD

**Issue by AzureEnigma** [cloudfoundry-incubator/cf-abacus#231]
When we submit one usage a x time and we attempt to submit another usage that is before that time, abacus will not aggregate the usage correctly. 

``` javascript
module.exports = {
	usage: [ 
		{
            "start":(new Date(Date.UTC(2016, 1, 2))).getTime(), 
            "end":(new Date(Date.UTC(2016, 1, 2))).getTime(),
             "region":"***",
            "organization_id":"***",
            "space_id":"***",
            "consumer_id":"***",
            "resource_id":"***",
            "plan_id":"***",
            "resource_instance_id":"***",
            "measured_usage": [
            
            ]
         }
         ]
}

{
	usage: [ 
		{
            "start":(new Date(Date.UTC(2016, 1, 1))).getTime(), 
            "end":(new Date(Date.UTC(2016, 1, 1))).getTime(),
            "region":"***",
            "organization_id":"***",
            "space_id":"***",
            "consumer_id":"***",
            "resource_id":"***",
            "plan_id":"***",
            "resource_instance_id":"***",
            "measured_usage": [
            
            ]
         }
         ]
}
```

When these two are submitted, the summary for the month is not the expected value.

**Comment by jsdelfino** [comment]
The usage aggregation functions are user defined.
What kind of service metrics are you using and how did you define your aggregate function?

**Comment by jsdelfino** [comment]
Also, could you share a test case illustrating the issue? I just tried and changed the Abacus demo to submit out of sequence usage and the usage summary was OK.

There is very little info in your initial issue description so with that little info it's difficult to say what's different in your environment that's causing the issue. Thanks!

**Comment by AzureEnigma** [comment]
My apologies for the poor example. I have one that uses abacus itself.

For this example, Im going to use the runtime linux-container, included in cf-abacus.

Assuming were starting on Feb 9th and I have abacus setup with a SLACK of 5D, Im going to submit usage for Feb 5th (4 days behind), Feb 8th (1 day behind), and Feb 7th (2 days behind).

With an empty database, I submit the following usages:

``` javascript
{
    usage: [ 
        {
            "start":(new Date(Date.UTC(2016, 1, 5))).getTime(), 
            "end":(new Date(Date.UTC(2016, 1, 5))).getTime(),
             "region":"region",
            "organization_id":"org1",
            "space_id":"space1",
            "consumer_id":"cloud-foundry-application:consumer1",
            "resource_id":"linux-container",
            "plan_id":"basic",
            "resource_instance_id":"id1",
            "measured_usage": [
              {
                "measure": "instance_memory",
                "quantity": 1073741824
              },
              {
                "measure": "running_instances",
                "quantity": 1
              }
            ]
         }
         ]
}

{
    usage: [ 
        {
            "start":(new Date(Date.UTC(2016, 1, 8))).getTime(), 
            "end":(new Date(Date.UTC(2016, 1, 8))).getTime(),
             "region":"region",
            "organization_id":"org1",
            "space_id":"space1",
            "consumer_id":"cloud-foundry-application:consumer1",
            "resource_id":"linux-container",
            "plan_id":"basic",
            "resource_instance_id":"id1",
            "measured_usage": [
              {
                "measure": "instance_memory",
                "quantity": 5368709120
              },
              {
                "measure": "running_instances",
                "quantity": 1
              }
            ]
         }
         ]
}
```

With these usages submitted, I grab the report at the end of Feb 9th, and get a monthly summary of 312, which is correct (1GB * 1 usage * 24 hours * 3 days + 5GB * 24 hours * 2 days) = 312.

However, then I submit the final usage:
``` javascript

{
    usage: [ 
        {
            "start":(new Date(Date.UTC(2016, 1, 7))).getTime(), 
            "end":(new Date(Date.UTC(2016, 1, 7))).getTime(),
             "region":"region",
            "organization_id":"org1",
            "space_id":"space1",
            "consumer_id":"cloud-foundry-application:consumer1",
            "resource_id":"linux-container",
            "plan_id":"basic",
            "resource_instance_id":"id1",
            "measured_usage": [
              {
                "measure": "instance_memory",
                "quantity": 2147483648
              },
              {
                "measure": "running_instances",
                "quantity": 1
              }
            ]
         }
         ]
}
```

When I grab the report, I expect 336 (1GB * 1 usage * 24 hours * 2 days + 2GB * 24 hours * 1 day + 5GB * 24 hours * 2 days), however, the report I receive says that the monthly summary of 96. 

``` javascript

{
  "organization_id": "org1",
  "resources": [
    {
      "resource_id": "linux-container",
      "plans": [
        {
          "plan_id": "basic/basic-linux-container/linux-rating-plan/linux-pricing-basic",
          "aggregated_usage": [
            {
              "metric": "memory",
              "windows": [
                [
                  null
                ],
                [
                  null
                ],
                [
                  null
                ],
                [
                  null,
                  {
                    "quantity": {
                      "consumed": 0,
                      "consuming": 5,
                      "since": 1454889600000
                    },
                    "cost": {
                      "burned": 0,
                      "burning": 0.0007,
                      "since": 1454889600000
                    },
                    "summary": 120,
                    "charge": 0.0168
                  },
                  {
                    "quantity": {
                      "consumed": 0,
                      "consuming": 2,
                      "since": 1454803200000
                    },
                    "cost": {
                      "burned": 0,
                      "burning": 0.00028,
                      "since": 1454803200000
                    },
                    "summary": 48,
                    "charge": 0.00672
                  },
                  null,
                  {
                    "quantity": {
                      "consumed": 0,
                      "consuming": 1,
                      "since": 1454630400000
                    },
                    "cost": {
                      "burned": 0,
                      "burning": 0.00014,
                      "since": 1454630400000
                    },
                    "summary": 24,
                    "charge": 0.00336
                  },
                  null
                ],
                [
                  {
                    "quantity": {
                      "consumed": 0,
                      "consuming": 2,
                      "since": 1454889600000
                    },
                    "cost": {
                      "burned": 0,
                      "burning": 0.00028,
                      "since": 1454889600000
                    },
                    "summary": 95.99999944444444,
                    "charge": 0.013439999922222222
                  },
                  null
                ]
              ]
            }
          ],
...
```

However, when I submit the same usages, but in chronological order, I get the correct summary
``` javascript
{
  "organization_id": "org1",
  "resources": [
    {
      "resource_id": "linux-container",
      "plans": [
        {
          "plan_id": "basic/basic-linux-container/linux-rating-plan/linux-pricing-basic",
          "aggregated_usage": [
            {
              "metric": "memory",
              "windows": [
                [
                  null
                ],
                [
                  null
                ],
                [
                  null
                ],
                [
                  null,
                  {
                    "quantity": {
                      "consumed": 0,
                      "consuming": 5,
                      "since": 1454889600000
                    },
                    "cost": {
                      "burned": 0,
                      "burning": 0.0007,
                      "since": 1454889600000
                    },
                    "summary": 120,
                    "charge": 0.0168
                  },
                  {
                    "quantity": {
                      "consumed": 0,
                      "consuming": 2,
                      "since": 1454803200000
                    },
                    "cost": {
                      "burned": 0,
                      "burning": 0.00028,
                      "since": 1454803200000
                    },
                    "summary": 48,
                    "charge": 0.00672
                  },
                  null,
                  {
                    "quantity": {
                      "consumed": 0,
                      "consuming": 1,
                      "since": 1454630400000
                    },
                    "cost": {
                      "burned": 0,
                      "burning": 0.00014,
                      "since": 1454630400000
                    },
                    "summary": 24,
                    "charge": 0.00336
                  },
                  null
                ],
                [
                  {
                    "quantity": {
                      "consumed": 345600000,
                      "consuming": 5,
                      "since": 1454889600000
                    },
                    "cost": {
                      "burned": 48384,
                      "burning": 0.0007,
                      "since": 1454889600000
                    },
                    "summary": 335.9999986111111,
                    "charge": 0.04703999980555556
                  },
                  null
                ]
              ]
            }
          ],
...
```

So it seems like submitting the usages out of order is what caused the problem.

**Comment by jsdelfino** [comment]
Thanks for the complete example! That makes more sense to me now.

If you're using the linux-container resource provided as an example in Abacus, yes you are correct that you'll need to submit usage in chronological order, as that linux-container example uses a simplistic usage accumulation formula like follows:
```
// a is the usage accumulated over time
// q is the new usage quantity
(a, q) => ({                                               
  consumed: a ? a.consuming * (q.since - a.since) + a.consumed : 0,
  consuming: q.consuming,
  since: q.since
})
```

That accumulation formula (and the aggregation formula is very similar too) will produce negative numbers if the time of the new usage quantity is older than the time of accumulated usage.

So, if you want to support processing usage in non-chronological order, you'll need to use a formula that keeps track of the recent history of (consuming, since) pairs in the accumulated usage object for example, and recomputes the correct total from that recent history when needed (or use any other math formula that you can come up with that is still incremental but doesn't depend on a chronological order).

Supporting that kind of history tracking goes beyond the goals of the linux-container example initially included in Abacus to illustrate time-based resource usage though... 

In general, I'd recommend to use your own metering, accumulation and aggregation formulas for any production needs instead of the simplistic formula samples provided in Abacus, as you may need more error checking, reporting, logging etc in your own formulas for example.

Hope that helps.

**Comment by KRuelY** [comment]
In order to take care of this issue, the formula for linux-container is updated. The dirty implementation is in my fork. I'll add some comments to explain how it works sometime tomorrow.

Metering plan: [linux-container](https://github.com/KRuelY/cf-abacus/blob/runtime/lib/plugins/provisioning/src/plans/metering/basic-linux-container.js),
Rating plan: [linux-container]( https://github.com/KRuelY/cf-abacus/blob/runtime/lib/plugins/account/src/plans/rating/linux-rating-plan.js).

The requirement to meter runtime usage becomes:

1.  To start a runtime usage, submit (No changes here) :
`[  {    "measure": "instance_memory",    "quantity": 536870912  },  {    "measure": "running_instances",    "quantity": 1  }]`

2. ** Updating a runtime**, i.e. Increasing the running instances from 1 to 4, requires you to first stop the current runtime and start a runtime usage like (1.). The submission time between stopping and starting runtime usage cannot be the same because collector will count them as duplicate.

3. Originally I thought of submitting negative running_instances to indicate the stop runtime usage or an additional flag to mark usage as a stop. Using flag is the cleaner implementation so @jsdelfino suggested that to stop runtime usage, submit:
` [  {    "measure": "instance_memory",    "quantity": 536870912  },  {    "measure": "configured_instances",    "quantity": 1  }, {    "measure": "running_instances",    "quantity": 0  }]`
Submit configured_instances instead of running_instances.

Would this solve the issue? Thoughts to make this better?

**Comment by hsiliev** [comment]
If I get this correctly the flow would be:

   1.

   Start: [ { "measure": "instance_memory", "quantity": 536870912 }, {
   "measure": "running_instances", "quantity": 1 }]
   2.

   Prepare for update: [ { "measure": "instance_memory", "quantity":
   536870912 }, { "measure": "configured_instances", "quantity": 2 }, {
   "measure": "running_instances", "quantity": 0 }]
   3.

   Update: [ { "measure": "instance_memory", "quantity": 536870912 }, {
   "measure": "running_instances", "quantity": 2 }]
   4.

   Stop: [ { "measure": "instance_memory", "quantity": 536870912 }, {
   "measure": "configured_instances", "quantity": 2 }, { "measure":
   "running_instances", "quantity": 0 }]


I'm not into the details, so sorry if my question seems naive, but why
can't we merge 2 and 3 from above into a single request. We already have an
additional configured and running flags that seems to mark stop, so why not
mark the update in the same way as well. Something like:

   1.

   Start: [ { "measure": "instance_memory", "quantity": 536870912 }, {
   "measure": "running_instances", "quantity": 1 }]
   2.

   Update: [ { "measure": "instance_memory", "quantity": 536870912 }, {
   "measure": "configured_instances", "quantity": 2 }, { "measure":
   "running_instances", "quantity": 2 }]
   3.

   Stop: [ { "measure": "instance_memory", "quantity": 536870912 }, {
   "measure": "configured_instances", "quantity": 2 }, { "measure":
   "running_instances", "quantity": 0 }]


Would be happy to hear this is not easy or not possible at all :)

2016-02-16 9:37 GMT+02:00 Kevin Yudhiswara <notifications@github.com>:

**Comment by piotrprzybylski** [comment]
I think what @KRuelY specified was that the stop event should include the information about instances and memory that are stopping - same as start, plus stop indicator. In your proposal at no.2, this information is lost (1 instance from the start). 
An alternative is the approach similar to Cloud Foundry events :

`[ { "measure": "instance_memory", "quantity": 536870912 }, {
   "measure": "instances", "quantity": 1 }, {"state": "STARTED"}]`

and

`[ { "measure": "instance_memory", "quantity": 536870912 }, {
   "measure": "instances", "quantity": 1 }, {"state": "STOPPED"}]`

**Comment by jsdelfino** [comment]
AIUI @KRuelY's proposal doesn't include a flag, it contains the following measures:
- configured memory per instance
- configured number of instances
- number of running instances

@piotrprzybylski's proposal includes the following:
- configured memory per instance
- configured number of instances
- whether the configured instances are running or not

IMO @KRuelY's proposal may be a bit superior as it'll also us to model situations where a subset of the configured instances is running (remembering that this Linux-container resource is supposed to be a more generic example than CF apps.)

Both proposals allow us to model the following situations:
- a container was using 0 instance before a time t and is using 1 instance after t
- a container was using 1 instance before a time t and is using 0 instance after t
and when combining two events:
- a container was using 1 instance before a time t and is using 2 instances after t
without relying on the events being presented in a chronological order.

@Hristo, in your step 2:
```
 Update: [ { "measure": "instance_memory", "quantity": 536870912 }, {
   "measure": "configured_instances", "quantity": 2 }, { "measure":
   "running_instances", "quantity": 2 }]
```
We wouldn't know by looking at this single event that the container was using 1GB before using 2GB, in order to figure this out we'd have to rely on step1 occurring before step2, which is not guaranteed (and the subject of this issue).

I'd like to suggest another proposal as well (as a translation of my above description of the state changes that we're trying to model, and including support for instance memory reconfiguration too).

The event would contain the following fields:
- previous configured memory per instance
- previous number of running instances
- current configured memory per instance
- current number of running instances

Translating this to JSON and illustrating the main state changes that we need to cover:
```
// Starting
[
  { measure: 'previous_instance_memory', quantity: 536870912 }
  { measure: 'previous_running_instances', quantity: 0 },
  { measure: 'current_instance_memory', quantity: 536870912 },
  { measure: 'current_running_instances', quantity: 1 },
}]

// Stopping
[
  { measure: 'previous_instance_memory', quantity: 536870912 }
  { measure: 'previous_running_instances', quantity: 1 },
  { measure: 'current_instance_memory', quantity: 536870912 },
  { measure: 'current_running_instances', quantity: 0 },
}]

// Scaling out
[
  { measure: 'previous_instance_memory', quantity: 536870912 }
  { measure: 'previous_running_instances', quantity: 1 },
  { measure: 'current_instance_memory', quantity: 536870912 },
  { measure: 'current_running_instances', quantity: 2 },
}]

// Reconfiguring
[
  { measure: 'previous_instance_memory', quantity: 536870912 }
  { measure: 'previous_running_instances', quantity: 1 },
  { measure: 'current_instance_memory', quantity: 999970912 },
  { measure: 'current_running_instances', quantity: 2 },
}]

```

Thoughts?

**Comment by piotrprzybylski** [comment]
I was wondering about the possibility of change not always being 'binary' from running to stopped and vice versa. With that in mind, I think your proposal captures wha is needed.

**Comment by KRuelY** [comment]
I'll try to implement your proposal. I think it should work, and it represents what an reconfiguration should be. An update shouldn't be a stop and then start. It would also avoid the double submission of 'stop and start' to do a reconfiguration.

**Comment by hsiliev** [comment]
The issue I see with the last proposal is with the previous fields and the
way cf-bridge works now. Having previous fields means that the resources
provider (cf-bridge or another component) will have to keep track of all
applications.

That goes in the direction of event retention DB between CF and Abacus that
feeds cf-bridge with 2 events - previous & current. We need the retention
DB for a number of reasons, but it is not trivial to get it running. Users
of cf-bridge may have to keep the old linux-container definition for some
time until we are ready to support the new approach.

Perhaps we can simply skip the previous fields and rely on the events order.

2016-02-16 19:04 GMT+02:00 Jean-Sebastien Delfino <notifications@github.com>
:

**Comment by hsiliev** [comment]
+1 in general

cf-bridge may need to skip the previous fields as I said above, and rely on
the events order. This would require some changes in the formulas I guess,
but that'll ease the migration to more stable solution.

2016-02-16 20:15 GMT+02:00 Kevin Yudhiswara <notifications@github.com>:

**Comment by piotrprzybylski** [comment]
Can the submission without the state change be handled, for example:
```
[
  { measure: 'previous_instance_memory', quantity: 536870912 }
  { measure: 'previous_running_instances', quantity: 1 },
  { measure: 'current_instance_memory', quantity: 536870912 },
  { measure: 'current_running_instances', quantity: 1 },
}]
```
This would be the case where CF start and buildpack_set events are the basis for the submission.

**Comment by KRuelY** [comment]
I'm looking for a way to update the bridge to use the new runtime formula.

The requirement to use the new runtime formula is to also submit previous usage. The changes from how to submit runtime usage:

```
// To start 1 instance consuming 1 GB
// old
[
  { measure: 'instance_memory', quantity: 1073741824 },
  { measure: 'running_instances', quantity: 1 }
]

// new
[
  { measure: 'current_instance_memory', quantity: 1073741824 },
  { measure: 'current_running_instances', quantity: 1 },
  { measure: 'previous_instance_memory', quantity: 0 },
  { measure: 'previous_running_instances', quantity: 0 }
]


// To update 1 instance consuming 1 GB to 2 instances consuming 2 GB
// old
[
  { measure: 'instance_memory', quantity: 0 },
  { measure: 'running_instances', quantity: 0 }
]
[
  { measure: 'instance_memory', quantity: 2147483648 },
  { measure: 'running_instances', quantity: 2 }
]

// new
[
  { measure: 'current_instance_memory', quantity: 2147483648 },
  { measure: 'current_running_instances', quantity: 2 },
  { measure: 'previous_instance_memory', quantity: 1073741824 },
  { measure: 'previous_running_instances', quantity: 1 }
]


// To stop an app
// old
[
  { measure: 'instance_memory', quantity: 0 },
  { measure: 'running_instances', quantity: 0 }
]

// new
[
  { measure: 'current_instance_memory', quantity: 0 },
  { measure: 'current_running_instances', quantity: 0 },
  { measure: 'previous_instance_memory', quantity: 2147483648 },
  { measure: 'previous_running_instances', quantity: 2 }
]
```

One of the thing we can do is to call [app_usage_events](http://apidocs.cloudfoundry.org/231/app_usage_events/list_all_app_usage_events.html) endpoint.
This has an issue as well because:

1.  We will need to scan the HUGE list of events to get the specific info that we want.
2.  The information about the previous consumption before the after_guid is lost.
3.  Looking at the usage, I saw that in the state STOP event, we have the previously configured memory_in_mb_per_instance and instance_count. This would not be the case when we have two START event in succession (Is this possible?).

@hsiliev and everyone, I would like to get your input and thought on how to make this changes.

Thanks!

**Comment by hsiliev** [comment]
The quick and dirty solution would be to use the old formula for the bridge. And then in the next release we can change it to keep the previous fields for every app. We already added a dbclient to it to store the last GUID we processed. This should work, since we don't expect out-of-order submissions because the app-usage-events are ordered.

To make things work with the new formula we need the check if the old instance and memory are present in STOP and RECONFIGURE events (cf scale). BUILDPACK change event should be fine since it is only a metadata change and does not affect the usage.

Not sure if there can be a two START events, but we can simply issue an usage event with the same current and previous - they should cancel each other iirc?

**Comment by jsdelfino** [comment]
Here are a few suggestions:

- keep the current formula in the bridge for now, to avoid rushing any change just before releasing, like I believe @hsiliev suggested
- look at the new proposed formula again and see if we really really need the previous memory usage in the case of scale-up/down
- record the memory consumption of each app in the bridge to know the previous usage on a scale-up/down
- instead of recording that in the bridge in front of the collector, retrieve it from the collector as that info is there in the collector DB (we could just add a new API endpoint to it to retrieve the last event for a given resource instance)
- submit a pull request to CF to have CF add that previous memory/instance usage info to scale-up/down app usage events

... and any creative combination or subset of these options, or any new ideas you guys may have to resolve this in an elegant way :)

**Comment by KRuelY** [comment]
All my changes are in the test plans, so they will not affect the linux-container that the bridge is using. 

What I mean by 2 START event in succession is reconfiguration / cf scale, sorry that I wasn't clear on this. 

I'll look into each suggestions, and see if I can come up with some more ideas later.

Thanks!

**Comment by KRuelY** [comment]
An update to this:

Collector is persisting previous memory usage which is at the collector's normalized usage db. I have this implemented in my [fork](https://github.com/KRuelY/cf-abacus/tree/previousUsage). The way I implemented this was to add another endpoint in the collector. I think it is cleaner to make use of the collector's dataflow output database, but currently the collector's GET endpoint isn't doing what I want(Get the last usage for an app) so a slight modification is needed. 

Another thing is that bridge will need to keep in memory usage cache to take care of multiple CF events in one page because the collector might not have processed the previous memory usage yet.

Any thoughts and suggestions?

**Comment by hsiliev** [comment]
I had a look at the CC code. We can extend the https://github.com/cloudfoundry/cloud_controller_ng/blob/master/app/repositories/runtime/app_usage_event_repository.rb with the previous memory and instances so we can get-rid of the in-memory cache storing all applications.

The needed data should be obtained in https://github.com/cloudfoundry/cloud_controller_ng/blob/master/app/models/runtime/app.rb with the help of `initial_value` function of the [Dirty plugin](http://sequel.jeremyevans.net/rdoc-plugins/classes/Sequel/Plugins/Dirty.html). The function & plugin are already used in `app.rb`.

**Comment by jsdelfino** [comment]
@KRuelY what's the status of this issue?

AIUI the Abacus pipeline is now able to handle out of order submission (even if the CF bridge doesn't yet leverage that capability.)

Also has there been any update from the CF runtime API group on adding a field with the previous usage to CF app usage events?

**Comment by hsiliev** [comment]
The thread in cf-dev: https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/J75LEAXU7H5ZRSI6GKSTANIBX4YFEOPY/#J75LEAXU7H5ZRSI6GKSTANIBX4YFEOPY

We might propose the change as a PR and check with Dieu if this is ok with the team.

**Comment by KRuelY** [comment]
Abacus is able to handle out of order submission if it is using the formula that is currently in the test-plan. The runtime example that we have is not using  the new formula because the bridge is using it right now. 

The change to the bridge is temporary on halt until we resolves how to fill in the previous fields. In the meantime, anyone who wants to use the formula to solves the out of order submission can use the formula in the test-plan.

**Comment by jsdelfino** [comment]
@hsiliev, Yes agree that the change in CC would be the way to go.

@hsiliev, @KRuelY, do you guys have an idea of what the CC code changes will look like for this?

Thanks!

**Comment by hsiliev** [comment]
The implementation in https://github.com/cloudfoundry/cloud_controller_ng/pull/569 produces the following events:
```
     {
         "metadata": {
            "guid": "906bdf61-8137-4386-9110-b4c20c26e88b",
            "url": "/v2/app_usage_events/906bdf61-8137-4386-9110-b4c20c26e88b",
            "created_at": "2016-03-29T12:07:13Z"
         },
         "entity": {
            "state": "STARTED",
            "previous_state": "STARTED",
            "memory_in_mb_per_instance": 512,
            "previous_memory_in_mb_per_instance": 256,
            "instance_count": 1,
            "previous_instance_count": 1,
            "app_guid": "8d962f04-1644-4546-8248-a11ba030d526",
            "app_name": "app1",
            "space_guid": "d84179b2-94d1-4882-8db6-915771151b49",
            "space_name": "diego",
            "org_guid": "89539eef-7de6-439d-b0e4-929ed72c7b2c",
            "buildpack_guid": "b767d046-303c-4a52-999a-381b0dd227f5",
            "buildpack_name": "staticfile_buildpack",
            "package_state": "STAGED",
            "previous_package_state": "STAGED",
            "parent_app_guid": null,
            "parent_app_name": null,
            "process_type": "web",
            "task_name": null,
            "task_guid": null
         }
      },
      {
         "metadata": {
            "guid": "68db5230-fb8a-4b3c-8089-12cd56738bc2",
            "url": "/v2/app_usage_events/68db5230-fb8a-4b3c-8089-12cd56738bc2",
            "created_at": "2016-03-29T12:07:13Z"
         },
         "entity": {
            "state": "STOPPED",
            "previous_state": "STARTED",
            "memory_in_mb_per_instance": 512,
            "previous_memory_in_mb_per_instance": 512,
            "instance_count": 1,
            "previous_instance_count": 1,
            "app_guid": "8d962f04-1644-4546-8248-a11ba030d526",
            "app_name": "app1",
            "space_guid": "d84179b2-94d1-4882-8db6-915771151b49",
            "space_name": "diego",
            "org_guid": "89539eef-7de6-439d-b0e4-929ed72c7b2c",
            "buildpack_guid": "b767d046-303c-4a52-999a-381b0dd227f5",
            "buildpack_name": "staticfile_buildpack",
            "package_state": "STAGED",
            "previous_package_state": "STAGED",
            "parent_app_guid": null,
            "parent_app_name": null,
            "process_type": "web",
            "task_name": null,
            "task_guid": null
         }
      },
      {
         "metadata": {
            "guid": "61b81840-73c8-47e8-ac28-d0b746854f62",
            "url": "/v2/app_usage_events/61b81840-73c8-47e8-ac28-d0b746854f62",
            "created_at": "2016-03-29T12:07:18Z"
         },
         "entity": {
            "state": "STARTED",
            "previous_state": "STOPPED",
            "memory_in_mb_per_instance": 512,
            "previous_memory_in_mb_per_instance": 512,
            "instance_count": 1,
            "previous_instance_count": 1,
            "app_guid": "8d962f04-1644-4546-8248-a11ba030d526",
            "app_name": "app1",
            "space_guid": "d84179b2-94d1-4882-8db6-915771151b49",
            "space_name": "diego",
            "org_guid": "89539eef-7de6-439d-b0e4-929ed72c7b2c",
            "buildpack_guid": "b767d046-303c-4a52-999a-381b0dd227f5",
            "buildpack_name": "staticfile_buildpack",
            "package_state": "STAGED",
            "previous_package_state": "STAGED",
            "parent_app_guid": null,
            "parent_app_name": null,
            "process_type": "web",
            "task_name": null,
            "task_guid": null
         }
      }
```

We will therefore send 3 events to Abacus - change, stop and then start.

@KRuelY Do you think the new formula will handle this?

**Comment by KRuelY** [comment]
I think that looks good! We will have to submit 3 submission: (The unit for the instance memory needs to be converted)

Scale up
1. { measure: 'current_instance_memory', quantity: 512 },
    { measure: 'current_running_instances', quantity: 1 },
    { measure: 'previous_instance_memory', quantity: 256 },
    { measure: 'previous_running_instances', quantity: 1 }

Stop
2. { measure: 'current_instance_memory', quantity: 0 },
    { measure: 'current_running_instances', quantity: 0 },
    { measure: 'previous_instance_memory', quantity: 512 },
    { measure: 'previous_running_instances', quantity: 1 }

Start
3. { measure: 'current_instance_memory', quantity: 512 },
    { measure: 'current_running_instances', quantity: 1 },
    { measure: 'previous_instance_memory', quantity: 0 },
    { measure: 'previous_running_instances', quantity: 0 }

**Comment by hsiliev** [comment]
Bridge now posts previous values with https://github.com/cloudfoundry-incubator/cf-abacus/commit/06ee12f1a4fc94b9febf660cce45e475f193c73c

**Comment by KRuelY** [comment]
Closing this since we have everything in place now. Thanks.
