### ISSUE TITLE
CF Bridge should persist lastRecordedGUID

### ISSUE THREAD

**Issue by danparsons** [cloudfoundry-incubator/cf-abacus#242]
My cf installation's event stream goes back roughly 30 days and contains almost 10,000 events. With the way abacus-cf-bridge is currently built, the app is forced to go through the entire event stream every time the app is restarted. Doing so takes in excess of 8 hours and causes the app's memory usage to balloon to 4GB and beyond, and until this process is done, no new events are recorded. This means I have to wait > 8 hours after a restart before abacus-cf-bridge can do useful work. If lastRecordedGUID persisted between app restarts, the app would almost immediately start processing new data.

**Comment by hsiliev** [comment]
We can store the last processed app event guid in the Abacus DB and read it back on bridge startup. 

In this way the bridge will cease to be simply a resource provider since it will gain access to the DB connection details of Abacus. Another approach would be to use a separate DB to store just the last GUID.

Thoughts?
