### ISSUE TITLE
CF Bridge memory usage is extreme

### ISSUE THREAD

**Issue by danparsons** [cloudfoundry-incubator/cf-abacus#243]
While abacus-cf-bridge is going through my 30-day, ~10k cf event stream, its memory usage grows to 4GB and beyond. This seems extreme, given what this app does. It's possible this memory usage may be related to the current architecture where processed GUIDs are cached in memory - see issue #242 regarding changing this to persistent storage.

**Comment by hsiliev** [comment]
One possible reason could be the use of interval instead of timer in https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/cf/bridge/src/index.js#L415

When Abacus pipeline is slow or with open circuits the interval timer will keep calling the slow reporting function.

I'll rework this to schedule execution when the previous one finish or error. In this way we should have only one reporting at a time.
