### ISSUE TITLE
Configurable Default Formulas

### ISSUE THREAD

**Issue by rajkiranrbala** [cloudfoundry-incubator/cf-abacus#286]
The default rate formula in the  abacus-rating-config  is

```js
 const rate = (p, qty) => new BigNumber(p || 0).mul(qty).toNumber();
```
This will not work if the qty is not a number.  This results in a problem where we tend to ignore certain metrics, having a quantity in the object format, that needn't be rated in the plan definition document.

Either these formulas can be redefined in such a way that it ignores quantity that is not a number or an other option would be to make this configurable (Provisioning Plugin?)

**Comment by betafood** [comment]
I think that's a good point to bring up, but the default accumulator/aggregator functions also assume that the quantity is a number, so the default rate function kind of follows suit in that regard. I think making a change to the rate default would also require a similar change to the accumulator/aggregator defaults.

I think having a configurable default may be a good idea since a rating plan does encompass a whole set of metrics rather than a single metric, so any new metric set may need a different rating plan.

**Comment by jsdelfino** [comment]
These formulas are default. We can consider them as the simplest examples of formulas one may want to use (for number quantities). I'm not sure about the value of making them support different types of quantities. If the given default doesn't fit your requirements, then it's easy, just don't use that default and use your own formula. Wouldn't that work?

**Comment by rajkiranrbala** [comment]
When there are large number of resources that share the same formula, and a very few which uses the default formula specified by abacus, wouldn't it be more easier if we made the default formula configurable?

**Comment by jsdelfino** [comment]
I'm actually looking into __removing__ the default, as having service providers rely on a potentially changing default makes metering unpredictable.

If you're looking for a way for multiple resources plans to share a formula (rather than a configurable default...), can't you simply have them share the same plan? or have your provisioning service generate the same formula (or generate the same Javascript require statement) into all the plans that need to share it?

I'm also going to change the title of this issue as it's confusing. We have default formulas now.

**Comment by maximilien** [comment]
We discussed this issue in IPM and the agreement is that if you feel strongly about this issue, please either comment here to make a better case or join the next IPM (next Friday).

Otherwise, we will close this issue.

**Comment by rajkiranrbala** [comment]
I go with @jsdelfino . Removing the defaults looks like a cleaner options to me.

**Comment by maximilien** [comment]
Ok, so closing.
