### ISSUE TITLE
Extension to allow submission of usage outside of the slack window

### ISSUE THREAD

**Issue by piotrprzybylski** [cloudfoundry-incubator/cf-abacus#300]
In some cases the submission flow can be interrupted due to some business errors, for example down time of service broker or expired credentials. In some cases the submission delay could be several days. 

The increase of the slack window size could address the problem, however the larger slack window size affects the whole system and storage requirements and thus is not right approach for exceptional cases. 

The preferred approach would be to extend abacus with the ability to submit usage outside of the slack window, potentially through a different endpoint / API.

**Comment by rajkiranrbala** [comment]
IMO the current structure of window in the usage document limits us from scaling up the slack window. 

For example a slack window of 5D would result in array something like [[{1}],[{1}],[{1}],[{3}],[{2}], with numbers representing number of elements. If we want to expand the slack window to 29D the the target window should look like [[{1}],[{1}],[{1}],[{29}],[{3}]]. 

Instead of using arrays for each window, if we use an object with indexes as keys, we can scale up. Also we do not have to have huge arrays. [{}, {}, { }, { '0' : 10 }, { '6' : 10 }, { '0' : 30 } ] indicates that there was an usage 7 days before the current day and for the current month.

**Comment by jsdelfino** [comment]
See my latest comment in issue #310, proposing to use a sparse matrix representation for time windows. That would solve this issue too as it'd allow us to use bigger slack window without wasting storage.

**Comment by jsdelfino** [comment]
Closing this issue as it'll be solved by #310 (without introducing an extension to submit usage outside the slack window, but by providing efficient support for much bigger slack windows).
