### ISSUE TITLE
Multiple cf-abacus-bridge, single database

### ISSUE THREAD

**Issue by dhrapson** [cloudfoundry-incubator/cf-abacus#335]
Hi, I'm looking for a way to calculate usage stats across multiple separate CF installations. I'm thinking of deploying a copy of cf-abacus-bridge to each CF installation, with the same underlying database behind. Is this likely to cause issues at the app or database level?
I took a look through the code and it didn't seem to me like there would.
Thanks
DHR

**Comment by hsiliev** [comment]
@dhrapson I haven't tried this, so I cannot provide concrete steps. 

However a few things that come to my mind:
   * the **"cache" db** that holds the app usage event ID reported by the bridge shall use a different DB for each cf-bridge instance. This can be changed in the manifest: https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/cf/bridge/manifest.yml#L14
   * **oauth clients** credentials might differ, so most probably you would need a different set of credentials for each cf-bridge instance (https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/cf/bridge/manifest.yml#L16-L17)
   * cf-bridge reports usage events using org guid, space guid, app guid and app usage event guid (https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/cf/bridge/src/index.js#L221-L226). There is a rare chance that some of these will **conflict** between different installations. In fact increasing the number of installations increases that chance. This can probably be addressed by adding unique identifier.

In terms of storage space having multiple DBs is not a big issue, since we keep there only 4 strings.
The configuration stuff however might be tricky since we do not support that scenario out of the box.
The mathematical chance to have collision in GUIDs is not big, but yet be aware that this might happen. I wonder if changing the resource_id or the plan_id can solve this potential issue.

**Comment by hsiliev** [comment]
I will close this issue. 

If you have more questions, found issues or just want to share your experience please reopen it.
