### ISSUE TITLE
abacus-webapp should expose a /info endpoint

### ISSUE THREAD

**Issue by csaroff** [cloudfoundry-incubator/cf-abacus#350]
Currently, abacus-webapp exposes a `/healthcheck` [endpoint](https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/utils/webapp/src/index.js#L42) which uses the eureka [healthcheck handler](https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/utils/eureka/src/index.js#L28-L60) to return a judgment of application health.  We should extend abacus-webapp to provide a `/info` endpoint that returns the application name, a description of the application and its version number.  All of this information could be gathered from the webapp consumer's package.json file.  I have a few implementation questions if this issue gains traction.

1.  Where should this code live?  abacus-webapp seems to just be a consumer/wrapper for other middlewares which are defined elsewhere.  Does it make sense to pollute the webapp code with this addition?

2.  I know that abacus-express already provides the application's currently running node version [in the headers](https://github.com/cloudfoundry-incubator/cf-abacus/blob/842d240b23484a044c4eae3833cdea63edb5466e/lib/utils/express/src/index.js#L647) of every request.  Should we explicitly provide the node version in the contents of `/info`'s returned object?

3.  Instead of extending abacus-webapp to provide this new endpoint, should we just add the application name, version number, and application description to the headers of every request similar to abacus-express's [processInfo](https://github.com/cloudfoundry-incubator/cf-abacus/blob/842d240b23484a044c4eae3833cdea63edb5466e/lib/utils/express/src/index.js#L324-L332)

4.  Are there other fields that seem useful to pull out of the webapp/express consumer's package.json file and provide to api consumers?

**Comment by jsdelfino** [comment]
My vote goes to a variation of option (3):

- Return the app version number in a header like we do for the node version, so that it's logged as that can be handy for problem determination (fetching it after the fact from an /info endpoint is a recipe for not retrieving the correct one IMO, and not of a great value compared to just looking at your build to see what version of the app you've deployed).

- I'm not sure about returning the app name and description as that'll be more data on the wire. Also... if making an OAuth authenticated HTTP request to your running app endpoint is the simplest solution for you to figure out its name and description, you may have a more serious development process issue :-)

**Comment by jsdelfino** [comment]
Actually it'll be better to do that in module abacus-vcapenv, which BTW already returns the app name in an X-App-Name header. I'll add the version too there. HTH.

**Comment by csaroff** [comment]
Thanks for the commit!
