### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by dhrapson** [cloudfoundry-incubator/cf-abacus#370]
Hi, I'm hoping to deploy cf-abacus at an enterprise where CouchDB is not permitted for data storage. 
MongoDB though I believe. I noted on your [blog](https://www.cloudfoundry.org/introducing-cf-abacus-part-3-of-3/) that MongoDB may become an option instead of CouchDB.
And I also see a bunch of commits, code and issues relating to MongoDB.
Can anyone tell me the level of Mongo support currently in cf-abacus (v0.0.5)?
Thanks
DHR

**Comment by hsiliev** [comment]
MongoDB is supported and tested to work with Abacus.

You can try it out by starting Mongo on you local machine, then:
```
. ./bin/localmongo
npm run rebuild
npm run demo
```

[mongoclient](https://github.com/cloudfoundry-incubator/cf-abacus/tree/master/lib/utils/mongoclient) is relatively new module that provides the support for Mongo. At present it supports replicas, but we never tested it with shards. In any case I would be glad to discuss feature requests or to fix bugs in it since I use it for our soon-to-be productive Abacus installation.

We have Mongo as part of our Travis [build](https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/.travis.yml) and you can also use the Concourse pipeline with MongoDB.

I think we need to add a new section on the DB support and how to configure it. I'll use this issue to do so.

**Comment by hsiliev** [comment]
Documented database configuration with 4833af53e282e3ac1d76a4c4db0e8cd71bc84aea
