### ISSUE TITLE
Submitting usage second time does not result in 409 conflict

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry-incubator/cf-abacus#395]
```bash
export DATE_IN_MS=$(date +%s000)
export BODY="{\"start\":$DATE_IN_MS,\"end\":$DATE_IN_MS,\"organization_id\":\"1\",\"space_id\":\"2\",\"resource_id\":\"linux-container\",\"plan_id\":\"basic\",\"consumer_id\":\"app:1fb61c1f-2db3-4235-9934-00097845b80d\",\"resource_instance_id\":\"1fb61c1f-2db3-4235-9934-00097845b80d\",\"measured_usage\":[{\"measure\":\"current_instance_memory\",\"quantity\":512},{\"measure\":\"current_running_instances\",\"quantity\":1},{\"measure\":\"previous_instance_memory\",\"quantity\":0},{\"measure\":\"previous_running_instances\",\"quantity\":0}]}"

curl -i -H "Content-Type: application/json" -X POST -d "$BODY" "http://localhost:9080/v1/metering/collected/usage"
curl -i -H "Content-Type: application/json" -X POST -d "$BODY" "http://localhost:9080/v1/metering/collected/usage"
```

The first POST results in 201. The second one should produce 409, but it also returns 201.

**Comment by KRuelY** [comment]
History: https://github.com/cloudfoundry-incubator/cf-abacus/pull/386.

I have created pull request https://github.com/cloudfoundry-incubator/cf-abacus/pull/394 to fix the 409 issue. We see 201 because when meter returns 409 conflict, collector will returns 201 because there is no duplicate detection in collector and the write to collector output db is a success. The change is to make it so that dataflow with no duplicate detection throw the 409.

**Comment by rajkiranrbala** [comment]
@KRuelY I just added a note for the commit https://github.com/cloudfoundry-incubator/cf-abacus/commit/ed6fd0eebf997632272a5d8885410fe05f57370c . I think we need to pick a different status code for slack errors.

**Comment by rajkiranrbala** [comment]
Solved with https://github.com/cloudfoundry-incubator/cf-abacus/pull/394
