### ISSUE TITLE
How to get Usage Data from CF

### ISSUE THREAD

**Issue by rjain-pivotal** [cloudfoundry-incubator/cf-abacus#41]
Abacus documentation says that you can submit usage data to Abacus for creating Billing/Metering. How do you get Usage Data from CF, the CF documentation in not every clear and neither is the Abacus documentation. 

The CF API's have send endpoint info, I couldn't find how to get the GUID? More practical examples would be really helpful, beyond the pouchdb, on how to extract the usage and the the complete pipeline example. 
http://apidocs.cloudfoundry.org/218/service_usage_events/list_service_usage_events.html

Thanks

**Comment by hsiliev** [comment]
We are currently building a prototype for reporting CF apps usage data to Abacus. You can have a look at the [bridge source](https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/cf/bridge/src/index.js).

What we currently do is to:
1. obtain oauth token
1. list app usage events
1. report [linux-container metrics](https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/config/resource/src/resources/container.js)

For now we basically report the memory used.

The same approach can be applied to service usage events. However I'm not aware of any useful metrics (besides the number of instances) present in the service usage events. This is due to the fact that CF does not (and should not) have an idea what the service actually does.

Instead the service providers can report the metrics they want to charge for to Abacus. This can happen in the service broker itself or in dedicated bridge that takes care to fetch the metrics from the broker and report to usage to Abacus.

**Comment by jsdelfino** [comment]
@rjain-pivotal Did that cover the Abacus part of your question?

It looks like you also had a question on how to use the CF app usage events (that's actually the title of this issue _How to get Usage Data from CF_).

I'd suggest to ask that question to the team working on that CF app usage events API if you can't find the info you need in the CF docs there: https://docs.cloudfoundry.org/running/managing-cf/usage-events.html

There was also a blog post on that topic recently: https://www.cloudfoundry.org/how-to-bill-on-cloud-foundry/

**Comment by piotrprzybylski** [comment]
There was also some discussion on the mailing list 
https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/message/EDBHWI7X7UCUAZVR7XNUWNTU27RKYN4R/
https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/NCPE42LVC7YZUQZ7GQGBFHTWVJOLVOUB/

**Comment by jsdelfino** [comment]
Doesn't look like there's anything else to discuss here. Please reopen if more discussion is needed.
