### ISSUE TITLE
Incorrect status 200 for error response

### ISSUE THREAD

**Issue by SukhilPatil** [cloudfoundry-incubator/cf-abacus#437]
aggregated usage response is throwing following error

``` json
 {
  "message": {
    "statusCode": 200,
    "error": "emplannotfound",
    "reason": "Metering plan for the metering plan id standard-linux-container is not found"
  },
  "statusCode": 200,
  "error": "emplannotfound",
  "reason": "Metering plan for the metering plan id standard-linux-container is not found"
}
```

Status code 200 is incorrect for an error response

**Comment by rajkiranrbala** [comment]
@SukhilPatil 

These errors were classified as business errors and service providers who submit usage cannot do anything about this. So they are given an information that the usage has been collected but not processed owing to business errors. These records can be found in the abacus-collector-error-usage database.

**Comment by hsiliev** [comment]
@rajkiranrbala I think the problem is caused by incorrect Abacus configuration in the provisioning plugin authentication. I want to investigate this specific case and see if we can make this surface as a real error instead of masking it as business error.

Apart from this edge case above, do you think it make sense to change the 200 code to `202 Accepted: The request has been accepted for processing, but the processing has not been completed.`? This is still a success code but also hints that we did not processed the usage.

**Comment by rajkiranrbala** [comment]
@hsiliev 

Status code 202 makes sense for records that were not processed. +1 for that. 

I thought we were using 201 as a response code even for usage with business errors. What @SukhilPatil posted as the response shows status code as 200, which is something that I do not understand. Is this because of the authentication issues?

**Comment by hsiliev** [comment]
Async buffer (rabbitmq) should hide these errors and delegate the retry to meter
