### ISSUE TITLE
How does the report generated by the demo relate to the entered usage and rate data?

### ISSUE THREAD

**Issue by dkoper** [cloudfoundry-incubator/cf-abacus#50]
We ran the demo. We looked at the input usage data, the resource configuration and the output report (summary), but it wasn’t clear how the data was calculated to result in that summary. I assume we don't understand well yet how to read the summary, or the rate sample file. Could you supply a simple rate file and usage data and show (maybe annotate a few lines or sections?)  how the content of the resource configuration is used to calculate the resulting summary?

**Comment by jsdelfino** [comment]
We'll need to update the API doc at some point but here's how this works in a nutshell:

- a resource provider controls how usage is metered, accumulated, aggregated, rated, summarized and charged through a set of Javascript functions (meter, accumulate, aggregate, rate, summarize, charge) that can be configured in a resource configuration JSON doc (see examples \[1\]\[2\]); these functions are called to process submitted usage as it flows through the Abacus meter, accumulator, aggregator and reporting services;

- the resource provider submits usage docs containing usage measures (e.g. number of API calls, or bytes of storage or memory);

- the resource provider's meter() function is called, given the usage measures, and is responsible for converting them to the metrics relevant for the particular resource (e.g. thousands of API calls, GB of storage, MB of memory);

- the provider's accumulate() function is called, responsible for accumulating (usually a simple sum) the particular metric over time (per sec, min, hour, day, month etc);

- the provider's aggregate() function is called next, responsible for aggregating (usually a sum as well) the particular metric at different levels under an organization;

- next, the provider's rate() function is called, responsible for computing the cost of the metric given the usage and the price of the particular metric;

- finally the summarize() and charge() functions are called to compute the final usage summary and corresponding charges, at the time the usage summary report gets produced.

- one final note, usage measures and metrics can be expressed as simple numbers (e.g. a decimal number representing a number of API calls) or compound data structures for more sophisticated usage metering schemes (e.g the ability to represent something like 'already consumed 153GB of memory and now consuming 3GB since 9:32am today'); the provider's meter, accumulate, aggregate etc functions are then free to interpret the data structure representing the metric however they want.

[1] https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/config/resource/src/resources/storage.js
[2] https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/lib/config/resource/src/resources/container.js

**Comment by jsdelfino** [comment]
The question was answered and added to an FAQ as well. Please re-open if more discussion is needed.
