### ISSUE TITLE
Invalid date arithmetics in aggregator module

### ISSUE THREAD

**Issue by PlamenDoychev** [cloudfoundry-incubator/cf-abacus#503]
Hi,

The method "shouldNotPrune" found in aggregator submodule is using an incorrect way to calculate the time. The method has to check if the current time exceeds 2 months + a configured slack window period. The issue becomes visible when you print the intermediate expressions in the console during unit-tests execution (npm test). We observed the following problems:

- The input parameter "time" should be parsed as number as if there is a space character in front the parsing using the standard Date class produce unrealistic dates (like year 27234)
- The way the time is calculated (adding 2 months + slack window period) is also wrong, Here we found 2 problems:
-- Adding the slack period using the "+" could lead to invalid type as its treated as String. So we observed dates like: [ 2016, 7, '301', 0, 0, 0, 0 ]. This is the result of adding 1 day to 30.7.2016
-- Even if the problem above is solved with parsing it will still lead to wrong dates as if you have a date like 31.08.2016 and you add 2 days you get 33.08.2016.
The issue seems not to be discovered till now as the used build in function Date.UTC.apply(null, prunescales) accepts invalid input and still returns numeric values. For some reason with the current input parameters the tests seem to pass although the dates are completely wrong.

The correct way to do such arithmetics should be by using some kind of library like moment.js that is currently used in other parts of the project instead of computing dates as pure numbers.

Best regards,
Hristo

**Comment by KRuelY** [comment]
Hey,

> -- Adding the slack period using the "+" could lead to invalid type as its treated as String. So we observed dates like: [ 2016, 7, '301', 0, 0, 0, 0 ]. This is the result of adding 1 day to 30.7.2016

Good catch. I never really look into this function and just take it for granted. This is definitely incorrect, and I believe your pull request will fix this issue.

> -- Even if the problem above is solved with parsing it will still lead to wrong dates as if you have a date like 31.08.2016 and you add 2 days you get 33.08.2016.

The javascript Date.UTC actually accepts outside of boundary value. This means that Date.UTC.apply(null, [2016, 8, 33]) is equivalent to Date.UTC.apply(null, [2016, 9, 1]), so I think that the logic still technically works since we're comparing the ms value.

> The correct way to do such arithmetics should be by using some kind of library like moment.js that is currently used in other parts of the project instead of computing dates as pure numbers.

+1 to this. It is always better to use the widely used moment instead of doing our own arithmetic.

I'll merge the pull request and close this issue.

Thanks!
