### ISSUE TITLE
Partitions not distributed evenly

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry-incubator/cf-abacus#536]
The DB partitions of the collector, aggregator and accumulator are not well distributed. This slows down the processing since we get far more docs in a single DB.

The partitioning also affects the request distribution since it is used in the post sinks. The result is that some of the apps are loaded more than the others, resulting in OOM due to too much connections. This prevents Abacus from scaling horizontally.

As an example:
  Collector:
  ```
  > db.getCollection("abacus-collector-collected-usage-0-201701").count()
  576202
  > db.getCollection("abacus-collector-collected-usage-1-201701").count()
  0
  > db.getCollection("abacus-collector-collected-usage-2-201701").count()
  29
  > db.getCollection("abacus-collector-collected-usage-3-201701").count()
  0
  > db.getCollection("abacus-collector-collected-usage-4-201701").count()
  0
  > db.getCollection("abacus-collector-collected-usage-5-201701").count()
  148049
  ```

  Aggregator:
  ```
  > db.getCollection("abacus-aggregator-accumulated-usage-0-201701").count()
  11949
  > db.getCollection("abacus-aggregator-accumulated-usage-1-201701").count()
  12824
  > db.getCollection("abacus-aggregator-accumulated-usage-2-201701").count()
  7270
  > db.getCollection("abacus-aggregator-accumulated-usage-3-201701").count()
  97202
  > db.getCollection("abacus-aggregator-accumulated-usage-4-201701").count()
  5627
  > db.getCollection("abacus-aggregator-accumulated-usage-5-201701").count()
  38778
  ```

**Comment by KRuelY** [comment]
This is because the usage submissions itself are not well distributed. Example: Instance/org A could have substantially higher number of submissions compared to instance/org B. All instance A would be handled by only accumulator 1 and organization A would be handled by only aggregator 1.

I think it is good to have a discussion on either how to handle too much submission for 1 instance / org or to allow apps that are not busy to help the busy app.

**Comment by rajkiranrbala** [comment]
In collector, the input key is just the client_id. So if a service provider submits a large number of usage records, even if it is distributed among multiple organizations, it ends up in the same partition. This shouldn't be a problem in collector since its a stateless instance and can be scaled. However, there might be performance issues with the database since all the documents are written to the same partition.

**Comment by hsiliev** [comment]
What actually bothers me is that we cannot simply add additional instances behind accumulator & aggregators that are loaded since we use our own partitioning, sink and basically load-balancing plus we have a lock to prevent concurrent modification.

If we could add instances then scaling would be a child's play.

**Comment by hsiliev** [comment]
Master now has rabbit as buffer to eliminate the problem with scaling collectors & meters. Therefore even if the DB partitions are not distributed evenly this should not affect load distribution.

We can implement the same buffer between meter & accumulator and then accumulator & aggregator.
