### ISSUE TITLE
Question for Modelling fixed prices + Usage based price

### ISSUE THREAD

**Issue by blinse** [cloudfoundry-incubator/cf-abacus#62]
Hi all, 

we are considering using cf-abacus as the usage-based billing component in our cloudfoundry installation. It seems like the usage documents with their various functions seem expressive enough for modelling a billing concept that is composed of

1) a fixed base price per month
2) usage based prices for api calls and storage
3) bonus in case of e.g. Service Level Agreement violations.

For 1) the service provider would simply submit only a single measured_usage subdocument for each service instance belonging to the service plan. 
for 2) this is the standard use case of cf-abacus
for 3) For each SLA violation a single measured_usage subdocument is submitted for a metric with a negative cost. 

The costs would be summed up using the summarize and/or charge functions in the cloud resource definition document. 

Still it is unclear to me how a change in service plans of a customer within a month could be modelled. In this case a fixed base-price (1) should not be charged for the entire month, but only for the active days of the service subscription. In contrast, usage based costs (2) are independent of the subscription period. 

One solution would be to require that the service owner sends a compensation measured_usage event.
Another solution would be to split the fixed price into daily prices and require the service provider to send a daily usage event as long as the subscription is active. 

Has anybody else faced this requirement with abacus. How did you solve it?

Thanks

Benedikt

**Comment by jsdelfino** [comment]
Great questions!

Looks like you have several (separate but related) questions here... I'll try to address them individually:

__1) Fixed price per month, accumulating over time__
I don't think you necessarily need the service provider to send you monthly events for this, as Abacus already supports metering of __time-based__ resource consumption without requiring regular events to report that consumption. 

Here's a suggestion:
- have the service provider send a single event at the beginning when the service gets enabled;
- model your usage like we do for app runtime metering, with a metric object representing something like 'consuming \<X\> since \<time\>' for example, instead of just a number; 
- model your cost in a similar way, with an object that represents something like 'costing \<Y\> since \<time\>', instead of just a number again;
- in your rate() function, simply multiply \<X\> by the configured metric price to produce \<Y\>; 
- in your charge() function, multiply \<Y\> by the number of months since \<time\> in the above;
- then just have the service provider send a second event when the service gets disabled and convert that event into a metric representing 'consuming 0 since \<time\>.

Our Linux 'container' sample resource \[1\] demonstrates a similar pattern with app runtime metering, for which we meter app memory consumption over time between an app start and stop. AIUI, the only thing that differs in this scenario is that you'll want to round the monthly charge to 0 or 1 * your fixed price.

__2) Discrete usage metering__ (.e.g. API calls)
Doesn't look like you had a question here.

__3) Billing discounts or credits__ (after an SLA violation for example)
Abacus records usage, meters and rates it, then computes usage and charge summary reports which can be fed to a __Billing__ system (separate from Abacus) responsible for billing the customer. Wouldn't these credits and discounts mostly be handled at that Billing level, rather than at metering, rating or service provider levels?

Is that billing discount / credit the capability you're really looking for? or are you looking for a more general usage __retraction__ mechanism, where usage (incorrectly) submitted during an outage or degraded SLA period would be compensated later?

__4) Plan change in the middle of the billing period__
We include the plan_id in the keys used to accumulate and aggregate usage, so two plans will give you two different entries, each will accumulate usage in its own period of time (e.g. plan A accumulates usage from Oct 1 to Oct 16, plan B from Oct 14 to Oct 31, and as I show here an overlap between the two is also possible). IIUC your scenario, to support this you'll want your charge() function to round the charge to a daily or hourly charge for example to allow for prorating instead of a monthly charge.

__5) Pricing change in the middle of the billing period__
We don't do that yet, but I need that too... and I'd like to implement it in the next few weeks (planning to do that once we have good support for all the other time window dimensions we've been working on recently). It should be easy to do by just adding a 'pricing version' or 'account state version' behind the plan_id in our 'accumulated_usage' doc keys. This is a particular case of a generic __landmark window__ pattern we've discussed recently in the team, where we want to accumulate and aggregate usage in ad-hoc non necessarily time-based usage buckets.

HTH... again you had several questions here so I'm hoping I've addressed some of them... Please comment again if needed and feel free to ask more :).

I'm also interested in any ideas you have to improve Abacus and make it easier to handle the scenarios you need to support!

[1] https://github.com/cloudfoundry-incubator/cf-abacus/blob/ec8847e9c558db69b0d5f5c06656b9084324db2c/lib/config/resource/src/resources/container.js

**Comment by jsdelfino** [comment]
No more comments in this discussion so closing for now. Please reopen if needed.
