### ISSUE TITLE
Reporting can't generate report for large orgs.

### ISSUE THREAD

**Issue by PlamenDoychev** [cloudfoundry-incubator/cf-abacus#646]
Hi colleagues,

   We observed that reporting plugin currently can't cope with large organizations. We tested with org which has a space with 1800 consumers and if we issue a request for org usage report, the reporting plugin fails to process the data. This usually causes a restart of the application with uses the reporting due to high (100%) CPU usage.

Regards,
Plamen Doychev

**Comment by hsiliev** [comment]
The last commit (https://github.com/cloudfoundry-incubator/cf-abacus/commit/dc60aa6582afb7dddb0b6b9cc7505b12fb534e44) in reporting enables the reporting to generate large reports (we've seen a 64MB report, containing 114000 consumers).

During our measurements we noticed that the DB (MongoDB in SAP case) is not a bottleneck. The problem seems to be caused by lots of data generated by the report, involving around 30 GCs, plus invoking `summarize` and `charge` functions for all consumers and time-windows.

Having the reporting in its current form, does not look like a good idea. We might want to redesign the way we generate the report. 

Some ideas:
* split the generation into org, space, consumer calls
* do not calculate seconds, minutes and hours windows
* do background processing

**Comment by hsiliev** [comment]
As a workaround we've tried to increase timeouts
```
# default 30 sec
CLUSTER_HEARTBEAT=120000
# default 60 sec
BREAKER_TIMEOUT=120000
```

The problem with this approach is that if the generation takes more than 30 seconds, OS, node, router, haproxy or load-balancer can close the connection.

**Comment by hsiliev** [comment]
A possible way forward is to use graphql only and skip generation of parts of the report. Especially consumers data might be a good candidate for that.

Another improvement is to get rid of the seconds, minutes and hours windows to reduce the DB and reporting size.

**Comment by eujungkim** [comment]
I tried to use graphql to resolve timeout problem, but using graphql was not the good solution for me.
I referenced demo/client/src/test/graphql.js file and used some query like this.
{  organization(organization_id:"379f81a7-d56a-4cee-8f84-4bc8daa681b3",time:1518480000000)
    {  organization_id,
       resources 
         { resource_id,
           aggregated_usage
           {  metric,
              windows{charge}}}}}
Using graphql makes time out, too.

**Comment by hsiliev** [comment]
We will remove time-windows for seconds, minutes and hours from accumulator/aggregator DBs with #310. This will reduce the DB size and speed-up the reporting a bit.

**Comment by eujungkim** [comment]
OK. I hope it will be soon.
When the new version is released, I'll apply and test it in my environment.

**Comment by hsiliev** [comment]
With d621559c9ffcf8033e7635fc47de6e061f2277bf reporting can be configured with `CONNECTION_TIMEOUT` to enable transfer of large documents. 

This should workaround the 502 response due to server timeout on Abacus side.
