### ISSUE TITLE
purgeCompensation

### ISSUE THREAD

**Issue by rdejana** [cloudfoundry-incubator/cf-abacus#65]
Hello,
I'm have trouble understanding exactly what the purge method is doing.  From my read of the code, apps that are started after the fetchCFApps call is completed are discovered are are reported as stopped.  Is the goal here only to report usage an applications we "knew" about when the bridge started?

**Comment by hsiliev** [comment]
Hi,

The purge compensation is meant to be executed after billing epoch start/creation. The epoch creation removes all usage events for stopped apps from the database, leaving trace only for the started ones. 

The epoch start is done with purge API call. Since ["there is the potential race condition if apps are currently being started, stopped, or scaled"](http://apidocs.cloudfoundry.org/219/app_usage_events/purge_and_reseed_app_usage_events.html), we compare the state of the CC and the usage events to check if there are misplaced usage events. 

For every app that is reported as started but not present in the CC we fire "stop usage" report.

Regards,
Hristo Iliev

**Comment by rdejana** [comment]
Thanks, that helps.
