### ISSUE TITLE
Error: Function .batch_post failed-fast due to open circuit-breaker

### ISSUE THREAD

**Issue by cfmagnum** [cloudfoundry-incubator/cf-abacus#654]
Getting following error in collector logs while submitting usage.

OUT 2017-06-06T14:03:01.179Z e-abacus-breaker 57 Function .batch_post calling back with error, { message: 'Function .batch_post failed-fast due to open circuit-breaker',
OUT   code: 500,
OUT   statusCode: 500 } - Error: Function .batch_post failed-fast due to open circuit-breaker

**Comment by hsiliev** [comment]
What version of Abacus do you have deployed? This happens for several reasons:
1. eval hanging or breaking node process (https://github.com/nodejs/node/issues/13464)
2. db issues
3. network issues

The workaround for #1 until it is fixed in node 6 is to apply the latest master and disable eval timeout (unset EVAL_TIMEOUT env.variable if you have it set)

Can you please check for `Script execution timed out` message in the logs of accumulator/aggregator?

**Comment by hsiliev** [comment]
Issue #1 that caused the problem most frequently was fixed in node 6.11.2. Closing the issue. Please reopen in case you still observe it on your side with newest node.

**Comment by hsiliev** [comment]
Reopening since we still need to:
* specify node 6.11.2 as minimum version for Abacus
* fix Travis and README to point to 6.11.2
* update npm shrinkwrap dependencies

**Comment by hsiliev** [comment]
Abacus now uses node 8.1.3 that fixes node.js racing condition
