### ISSUE TITLE
Unusually large number of partitions 

### ISSUE THREAD

**Issue by rajkiranrbala** [cloudfoundry-incubator/cf-abacus#69]
I was working on some APIs to query data from accumulated-usage-log database. Queries that took seconds to execute took unusually large amount of time after merging with the latest source. Also the logs showed that many requests failed owing to connection time out. 

From the logs I could see unusually large number of partition maps being created. I modified the dbserver to see the number of requests that are being sent to the db while running the demo. The [latest commit](https://github.com/cloudfoundry-incubator/cf-abacus/commit/174a62d5b8a3c0e5d886e732a26bf4db2154334b)  had 773 requests to the db, while an [earlier commit](https://github.com/cloudfoundry-incubator/cf-abacus/commit/be64bc50408e523671a24670d4d16fdadfd0fb7c) had only 38 requests 

Here is the code that I added to the dbserver to count the requests

```javascript
const debug2 = require('abacus-debug')('request-counter');
let i = 0;
app.use(function(req,res,next) {
        i++;
        debug2('[%s] [%s] %s', i, req.method, req.url);
        next();
});
```

I was not able to attach the log files here and hence I uploaded it to dropbox. You can find the [Logs Here](https://www.dropbox.com/sh/qo1e1ypwgslua0r/AAAnArjPNnroDDLcp_vM2UFJa?dl=0)

**Comment by sasrin** [comment]
> Queries that took seconds to execute took unusually large amount of time after merging with the latest source.

We saw the same problem with demo client at Travis [1]. We are now taking more than 250 ms to retrieve usage report and agree with you that this needs more investigation.  

[1] Github issue #68

**Comment by jsdelfino** [comment]
Yup seeing the same issue here as well.

**Comment by BetaFood** [comment]
One of the issues here lies in the partitioning logic. Specifically when determining the periods from the bounds in a range Operation.
```javascript
const periods = range(bounds[0], bounds[1] + 1, bounds[1] < bounds[0] ?
        -1 : 1);
```
Since this logic does a pure +1 or -1 as a step regardless of the period function passed in, db names of 201499, 201498 will happening. It would good to make this logic extendible since limiting it would limit all use of partition to a monthly date range.

This range is used in dbpartitions() inside of dbclient and subsequently pool(). pool() eventually calls the the default dbcons() function(in this case, it's using the default)
```javascript
const dbcons = (uri, opt, cb) => cb(undefined,
  /:/.test(uri) ? new PouchDB(uri, defaults(opt || {}, {
    ajax: {
      rejectUnauthorized: false
    }
  })) : new PouchDB(uri, defaults(opt || {}, {
    db: memdown
  })));
```
Calling PouchDb creates the database in this case. So querying the range of [201401, 201501] will create about 100 databases before it tries to do the query.

Since reporting is doing a descending range query of a limit of 1, it should ideally stop once it finds its first record(or if it finds nothing). rangeOp has such logic for doing that
```javascript
 if(opt.limit && accum.length === opt.limit)
          return rcb(undefined, accum);
```
However, as shown above. The list of dbhandles is already created, so this line only stops subsequently queries into each database.


There's a couple of things here to consider:
* The range creation based upon the bounds from the period
  * Currently, the range creation is using a simple step of +1 or -1. This results in creating dbhandles for databases with invalid months.
  * This functionality would need to be extendible to prevent any limitations in the partitioning module
* Databases are being created on an allDoc requests.
  * Databases should probably not be created on a retrieval operation since they would have no data to return in that case
* The query itself
  * The query does a range operation from the month of the time passed to the beginning of the year before the time passed in. Since the time windows will be keep track in a single document up to the previous year, the query starts with the beginning of the last year
    * 1444246062000 would do a query from 201401 to 201510
  * We might have to understand how far we look in terms of a report. If by chance a report for an organization is asked for 2015-10, would it make sense to return 2014-04 assuming that's the latest usage of that org?

I'm thinking that the second point would solve this current issue, but that we would need to also solve the first issue(since a bulkDocs request could create many databases with invalid months).

Thoughts?

**Comment by jsdelfino** [comment]
OK, if you want I can look into the issues in the dbclient and partitioning code, specifically:
- run the time period range over a set of valid time periods (as 201499 is not a valid period)
- not create a DB partition if it doesn't exist and the requested operation is a read

With respect to how far back we want to look for a report? I'm thinking that we could stick to the requested month (and if you had no usage this month then just return 404), but that may deserve a broader discussion. Would you mind posting to cf-dev about that part, so we can continue the discussion there?

**Comment by jsdelfino** [comment]
Looks like we need to upgrade to a more recent version of PouchDB to leverage the ability to skip the DB creation. Working on it...

**Comment by jsdelfino** [comment]
We're now using PouchDB 5.0.0. We're still iterating through too many databases but at least they're not created automatically anymore so that should help.

**Comment by jsdelfino** [comment]
To fix the time period range issue, I'm going to change the `period` format from YYYYMMDD to 'number of days since time 0' and the `epoch` format from YYYYMM to 'number of months since time 0 (time 0 new Date(0), basically Jan 1 1970). The db naming function will just convert the `epoch` back to a YYYYMM db name to keep these names user friendly.

**Comment by jsdelfino** [comment]
Closing as this is now fixed. I didn't have to change the epoch and db naming after all (keeping it in the format YYYYMM), only changed the time period to a number of days.
