### ISSUE TITLE
Cloud Foundry Deployment changes

### ISSUE THREAD

**Issue by Nishanksingla** [cloudfoundry-incubator/cf-abacus#739]
Under "Deploying to Cloud Foundry" section in the readme, it's written, "Please adjust to your particular Cloud Foundry deployment environment." 

Can anyone please tell me where and what changes do I have to make according to CF environment?

I have deployed all the abacus application, after that, I deployed "abacus-cf-applications" and I have updated the manifest file with AUTH_SERVER, CF_CLIENT_ID and CF_CLIENT_SECRET but in the logs the cf-application, I am getting following errror

> e-abacus-paging 55 Missing CF token
>    2017-09-19T14:55:34.24-0700 [App/0] OUT 2017-09-19T21:55:34.249Z e-abacus-oauth 55 Error getting OAuth bearer access token, { message: 'Unable to get token endpoint from oauth server' } - Error: Unable to get token endpoint from oauth server

**Comment by hsiliev** [comment]
Hi @Nishanksingla,

In app bridge we use the following CF environment:
```
### CF installation ###
API: https://api.<domain>:443
AUTH_SERVER: https://api.<domain>:443
JWTALGO: RS256
JWTKEY: -----BEGIN PUBLIC KEY-----
<  UAA public key >
-----END PUBLIC KEY-----

PRIMARY_DOMAIN: <domain>

### Abacus landscape ###
CF_CLIENT_ID: abacus-cf-bridge
CF_CLIENT_SECRET: <secret>
CLIENT_ID: abacus-linux-container
CLIENT_SECRET: <secret>
COLLECTOR: abacus-usage-collector
EUREKA: abacus-eureka-plugin
SECURED: true

### Abacus specific ###
EVAL_VMTYPE: vm
DEBUG: e-abacus-*
NODE_MODULES_CACHE: false
NODE_OPTS: --max_old_space_size=256
BATCH_SIZE: 50
THROTTLE: 100

### DB ###
DBALIAS: db-common
DBCLIENT: abacus-mongoclient
```

I separated the variables in several groups:

- CF specific
   can be obtained from your deployment manifest or the CF CLI target.
- Abacus landscape
   includes installation specific variables: UAA client ids and secrets and application names (if you ever need to changed them).
- Abacus specific
   related to scaling, debugging, plan handling
- DB
   here you can specify what DB to be used (service or external URL), type of database and finally specify if you need app-level (poor-man) sharding if needed.

The accumulators use the following set of variables:
```
ACCOUNT: abacus-account-plugin
AGGREGATOR: abacus-usage-aggregator
API: https://api.<domain>:443
AUTH_SERVER: https://api.<domain>:443
BATCH_SIZE: 50
CLIENT_ID: abacus
CLIENT_SECRET: s3cr3tpass?system!
CONF: large
DBALIAS: db-common
DBCLIENT: abacus-mongoclient
DEBUG: e-abacus-*
EUREKA: abacus-eureka-plugin
EVAL_TIMEOUT: 800
EVAL_VMTYPE: vm
JWTALGO: RS256
JWTKEY: -----BEGIN PUBLIC KEY-----
<UAA public key>
-----END PUBLIC KEY-----

NODE_MODULES_CACHE: false
NODE_OPTS: --max_old_space_size=256
PRIMARY_DOMAIN: <domain>
PROVISIONING: abacus-provisioning-plugin
REPLAY: 1800000
SAMPLING: 1h
SECURED: true
SLACK: 5D
THROTTLE: 100
```

Note that we have `SAMPLING` above, that means accumulator will create a new accumulated data document every hour. This reduces the amount of data in the DB, but also means we can lose 1h of data in case of crash, corrupted database, etc.

Also we do a replay of our input DB to guarantee no data is stuck in our input DBs by supplying `REPLAY` with a value of 30 minutes. This means that we allow our apps to be down for updates for up to 30 minutes.

**Comment by Nishanksingla** [comment]
Hi @hsiliev 

Thank you for the information. I have few doubts.
I am writing the values in the angle brackets which I have understood, please correct me If I am wrong.

In CF Installation section: 

API: < CF API Link( https://api.system.....) >
AUTH_SERVER: < UAA server link( https://uaa.system...) >

In Abacus landscape

CF_CLIENT_ID: <UAA client ID>
CF_CLIENT_SECRET: <UAA client secret>
CLIENT_ID: <???>
CLIENT_SECRET: <???>

What is Client_ID and Client_Secret and from where to get values for these fields?

Also, these configurations are for cf app bridge, what changes do I have to make in abacus applications for cloud foundry. Please help me with that also.

**Comment by hsiliev** [comment]
There are several UAA clients Abacus needs to function correctly in secured mode. More info on security concept doc: https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/doc/security.md

All of these are created by our Concourse pipeline: https://github.com/cloudfoundry-incubator/cf-abacus/tree/master/etc/concourse

Additionally each Resource Provider needs to authenticate via token. We automate this via Abacus broker project: https://github.com/cloudfoundry-incubator/cf-abacus-broker

**Comment by Nishanksingla** [comment]
Thank you for the information. 
After looking at all the code and documents, I am stuck at one thing. 
As CouchDB bosh release is not out yet, how can I run the pipeline without the database ?

And if I do `create-db-service` field as `false` in `deploy-pipeline-vars.yml`, will the pipeline deployment use `abacus-pouchserver` application for storing everything?

**Comment by hsiliev** [comment]
You can:
- use user-provided services
- specify DB URL directly with `DB` environment variable in manifest

Setting `create-db-service: false` will help you do each of the above, as you most probably won't need a DB service to be created in this case.

**Comment by Nishanksingla** [comment]
Ok. 
For the demo purpose, how can I use `abacus-authserver-plugin` with `cf-app-bridge application`? 
How to create client_id and client_secret for `cf-app-bridge application` in `abacus-authserver-plugin`?
Also, How to point to `abacus-pouchserver` in cf-app-bridge manifest.yml?

Initially, I deployed all the abacus application and app bridge application. I was getting the following error. 

 `Error getting OAuth bearer access token, { message: 'Unable to get token endpoint from oauth server' } - Error: Unable to get token endpoint from oauth server`

I would appreciate a lot if you can help.

**Comment by hsiliev** [comment]
app-bridge cannot work without CF Cloud Controller (CC) as it pulls events with admin read-only scope. 

You could run app-bridge with authserver-plugin, but you still need to connect app-bridge to CF CC. And the token validation in CC should not allow you to use tokens issued by authserver-plugin instead of UAA to fetch the app-usage events.

So I would recommend to use UAA instead.

Have in mind that pouchserver is used for testing and developing Abacus. You should be able to use it by simply deploying it to CF and using `DB: abacus-pouchserver` in app manifests. If you are using HTTPS you might need to specify the full path: `DB: https://abacus-pouchserver.<domain>:443`

**Comment by Nishanksingla** [comment]
Ok. 
What I have done is that for app-bridge application I have register `abacus-cf-applications` uaa client to talk to CC and I have entered the following
```
    CF_CLIENT_ID: abacus-cf-applications 
    CF_CLIENT_SECRET: < my genereated secret >
```

For resource provider authorization using `authserver-plugin` I have entered the following configuration which comes as default as I don't know how to create client_id and client_secret with authserver-plugin. I hope both values are right.

```
 CLIENT_ID: abacus-linux-container
 CLIENT_SECRET: secret
```

Please let me know if this is right.

**Comment by hsiliev** [comment]
Seems in synch with the config we use (above)

**Comment by Nishanksingla** [comment]
My only question is 
So the client_secret value is "secret"? 
Client_ID = "abacus-linux-container" and Client_Secret= "secret" is already added in authserver-plugin or do I have to add somehow ?

**Comment by hsiliev** [comment]
The pipeline (etc/concourse) uses the following script to create UAA users:
https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/etc/concourse/scripts/create-uaa-clients#L42-L49

The default client names we use are:
SYSTEM_CLIENT_ID=abacus
BRIDGE_CLIENT_ID=abacus-cf-applications
CONTAINER_CLIENT_ID=abacus-linux-container
HYSTRIX_CLIENT_ID=abacus-hystrix

The client names and secrets can be changed. What's important is that they contain the right scopes, that we use for authentication/authorization.

**Comment by Nishanksingla** [comment]
I am not using UAA for authorization now just the `abacus-authserver-plugin `. I have created CF_Client_Id and CF_Client_Secret in UAA that can read cloud controller API's.  Rest of the authorization and authentication stuff I am trying to do with `abacus-authserver-plugin `. 

That's why I want to know the values of Client_ID and Client_Secret for `abacus-authserver-plugin` as I am not creating UAA client right now.

**Comment by hsiliev** [comment]
Arbitrary values would do. As I said we care for the scope. Client ID and Secret are used for authentication and Auth Server does not support any as it is a dummy implementation as all Abacus plugins.

**Comment by hsiliev** [comment]
@Nishanksingla Any progress or new issues with the setup?

**Comment by Nishanksingla** [comment]
Hey @hsiliev 
Thanks for checking in. Unfortunately, no progress. 
This what I am getting again and again. 

> Error getting OAuth bearer access token, { message: 'Unable to get token endpoint from OAuth server' } - Error: Unable to get token endpoint from OAuth server

In `cf app bridge application` as well as `abacus-usage-collector`. 

In `cf app bridge application`, I am also getting `Missing resource provider token`

I don't what's going wrong, I have created UAA clients for the resource provider, system, and CF_Client. 

Following is my manifest file for `Cf app bridge application`

> applications:
> - name: abacus-cf-applications
>   host: abacus-cf-applications
>   path: .cfpack/app.zip
>   instances: 1
>   memory: 512M
>   disk_quota: 512M
>   env:
>     CONF: default
>     DEBUG: abacus-cf-*, e-abacus-*
>     COLLECTOR: https://abacus-usage-collector.run.aws-*****
>     EUREKA: https://abacus-eureka-plugin.run.aws-*****
>     API: https://api.system.aws-*****
>     DB: https://abacus-pouchserver.run.aws-*****
>     DBCLIENT: abacus-couchclient
>     CF_CLIENT_ID: abacus-cf-applications 
>     CF_CLIENT_SECRET: < SECRET >
>     NODE_MODULES_CACHE: false
>     SECURED: true
>     AUTH_SERVER: https://uaa.system.aws-*****
>     CLIENT_ID: abacus-linux-container
>     CLIENT_SECRET: < SECRET >
>     JWTKEY: |+
>       -----BEGIN PUBLIC KEY-----
>            public key
>       -----END PUBLIC KEY-----
>     JWTALGO: RS256
> 

I am not getting what oauth server is doing. Also, cf-app-bridge or any other application is even talking to UAA or not?

**Comment by hsiliev** [comment]
Can you post the scopes of your clients? I want to check that they are correct. You can also see if oauth is working by adding `abacus-oauth*` to `DEBUG`.

Due to #627 you have to specify urls like this `https://<host>:443`

Not sure if this is paste & formatting problem, but `DEBUG` should have wildcards at the end of the strings: `e-abacus*` for example

**Comment by Nishanksingla** [comment]
Below are the commands that I used to Uaac Clients:
**Resource provider**
> uaac client add abacus-linux-container --name abacus-linux-container --authorized_grant_types client_credentials --authorities abacus.usage.linux-container.write,abacus.usage.linux-container.read --scope abacus.usage.linux-container.write,abacus.usage.linux-container.read --secret < SECRET >

**System**
> uaac client add abacus --name abacus --authorized_grant_types client_credentials --authorities abacus.usage.write,abacus.usage.read --scope abacus.usage.write,abacus.usage.read

CF_Client to take to cloud controller api
> uaac client add abacus-cf-applications --name abacus-cf-applications --authorized_grant_types client_credentials --authorities cloud_controller.admin

Yeah, that was the formatting issue. I will add 443 and will try again but the urls point to 443 ports only.

**Comment by Nishanksingla** [comment]
I made it work. The problem was in naming convention. 
In our case AUTH_SERVER has its own endpoint which starts with `https://uaa.system...` but when I looked at the code, the code makes a "GET" a call at the CF API endpoint(which is `https://api.system.../v2/info`) and fetch the auth server endpoint which again is `https://uaa.system...`

**Comment by hsiliev** [comment]
@Nishanksingla Good point. Created a new issue to remove the API endpoint.

I'll close this issue, but if you have more questions feel free to reopen it.

**Comment by Nishanksingla** [comment]
Hi @hsiliev 

Thank you for all the help. I appreciate it. 

Now the authentication and authorization stuff is working, I am getting following error 

> The usage submitted is older than 600000 milliseconds

After the changing the slack_window to 5d still, I am getting the same error. 

> The usage submitted is older than 432000000 milliseconds.

I don't think I understand the slack_window completely. According to what I understood, Slack_window is the time difference between last usage document and current usage document. 
But each usage document has 2 times, start and end.
Please correct me if I am wrong. 

I also ran the `abacus-get-usage.sh ` script for many org_id's but always I am getting following empty response 

> {
>   "id": "k/001fd8e7-0162-4eeb-84d9-30d1f4110c9c/t/0001506636149539",
>   "organization_id": "001fd8e7-0162-4eeb-84d9-30d1f4110c9c",
>   "start": 1504224000000,
>   "end": 1506636149539,
>   "resources": [],
>   "spaces": [],
>   "windows": []
> }

**Comment by hsiliev** [comment]
Slack is used to allow Resource Providers to send usage from previous month. They might be slow (or unable to send) due to crashes, network partitioning, updated. 

A workaround would be to extend this window to day `31d`. This will allow you to fetch some events (but probably not all).

The solution is to start a billing epoch for CF:
https://github.com/cloudfoundry-incubator/cf-abacus/wiki/Installation#billing-epoch

This will reset all events to the current time, so bridges can transfer them. It also makes them fit to the slack window.

**Comment by Nishanksingla** [comment]
Hi @hsiliev,

Thank you for the help. I am able to solve the issue and run the abacus. 
Now I have to usage summary reports. 
The only problem I am facing now that How to read usage summary report? and How to make sense of it?. 
There are so many fields that it is getting hard to understand it. I tried to find the documentation but couldn't find anything. Also, I read the usage summary report API but was not able to find the answers.

I would appreciate a lot if you can help me regarding this.

**Comment by hsiliev** [comment]
The report contains 3 different roots:
* the organization as a whole
* breakdown for different spaces in the org
* breakdown for resources. 

You can drill-down based on what your UI or integration layer is interested in. If you don't need all the data I guess you can go with just aggregated usage per resource. This should give you monthly usage for linux-container, object-store, PostgreSQL or whatever resource providers submit data in Abacus.

The report works with time windows structures documented here:
https://github.com/cloudfoundry-incubator/cf-abacus/wiki/Time-Windows

To minimize the report size you can use GraphQL:
https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/doc/api.md#graphql-usage-query

**Comment by Nishanksingla** [comment]
I understand the format of the report but I have few questions. 
1.) Below is the sample window which I got in a report of an organization 

> "windows": [
>     [
>       null
>     ],
>     [
>       null
>     ],
>     [
>       null
>     ],
>     [
>       {
>         "charge": 0.02621032444722222
>       },
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null
>     ],
>     [
>       {
>         "charge": 0.02621032444722222
>       },
>       null,
>       null
>     ]
>   ]

The `window` is Array of 5 Arrays in which 4th array is Minute's and the 5th array is Seconds according to `https://github.com/cloudfoundry-incubator/cf-abacus/wiki/Time-Windows`. In my case minute array is always of length 32 and seconds array is of length 3. 
I don't understand these lengths and what's the data inside each array represents.  

2.) When I am fetching a usage summary report of an org with the org_id, I am getting the report from which date to which date? Start and end is a very big number. 

3.) Why is 'consumed' a big negative number? If I look inside resources->plans->aggregated_usage>windows, I see the following object which I am not getting. 

>  "quantity": {
>                       "consuming": 64.75,
>                       "consumed": -4112402000
>                     },
>                     "cost": {
>                       "price": 0.00028,
>                       "consuming": 64.75,
>                       "consumed": -4112402000
>                     },
>                     "summary": 93.60830159722222,
>                     "charge": 0.02621032444722222
>                   },

The report is very confusing to get.

**Comment by hsiliev** [comment]
Actually your daily window is from 32 days. I guess you set SLACK to 32 days, since there is 1:1 connection between the two. Abacus has to store 32 days back in time to allow usage to be submitted 32 days back in time.

The report is always from a month: from start of the month to the date you provided in the request. If no date is provided, the current month (and end-time = now) is used. 

`consumed` is an internal state, keeping the "memory balance". The sign is used to keep track if the memory is used or unused (app started or stopped). In short: you should not use its value.

**Comment by Nishanksingla** [comment]
I have set the SLACK to 31d as you suggested. What is the order of five arrays in windows array? Is it `seconds, minute, hours, days and months`  or  `months, days, hours, minute and seconds`. 
According to what you are saying it's the first order but according to the [https://github.com/cloudfoundry-incubator/cf-abacus/wiki/Time-Windows] (https://github.com/cloudfoundry-incubator/cf-abacus/wiki/Time-Windows) it's the second order. 
Please correct me. 

So if I remove the SLACK from the manifest file, I won't see 32 length array. Let me give it a try.

**Comment by HristoDobchev** [comment]
Hi,

The correct order is: seconds, minute, hours, days and months. The example on the wiki is a conceptual representation as JSON and is not the real structure. I will edit it to avoid confusion in the future.

Best regards,
Hristo

**Comment by Nishanksingla** [comment]
Ok Thanks.

So I changed SLACK to 5D and following is the windows that I got. It seems that the day array is always one plus the number of slack days. I don't know why and don't know the meaning of each entry.
              
> "windows": [
>                 [
>                   null
>                 ],
>                 [
>                   null
>                 ],
>                 [
>                   null
>                 ],
>                 [
>                   null,
>                   null,
>                   null,
>                   null,
>                   null,
>                   {
>                     "quantity": {
>                       "consuming": 43.5625,
>                       "consumed": -2766741500
>                     },
>                     "cost": {
>                       "price": 0.00028,
>                       "consuming": 43.5625,
>                       "consumed": -2766741500
>                     },
>                     "summary": 138.48034722222224,
>                     "charge": 0.038774497222222225
>                   }
>                 ],
>                 [
>                   null,
>                   {
>                     "quantity": {
>                       "consuming": 43.5625,
>                       "consumed": -104389341500
>                     },
>                     "cost": {
>                       "price": 0.00028,
>                       "consuming": 43.5625,
>                       "consumed": -104389341500
>                     },
>                     "summary": 1183.9803472222222,
>                     "charge": 0.3315144972222222
>                   }
>                 ]
>               ]

But still, I don't get the meaning of each entry in each array. Like what does the 6th entry of day array means?

**Comment by HristoDobchev** [comment]
Hi,

I am preparing a wiki page that would explain the time windows better. However it is still under development and I will just paste here a part of it:

# <a name="time_windows"></a>Time windows

Usage accumulation happens in the so called _**time windows**_. These are predefined timeframes that span back from the usage  __**processing time**__ (the time when the usage hit Abacus). The current periods are [second, minute, hour, day, month]. Each usage consumption is accumulated to a time window if its _**end time**_ falls in the same time interval.

Example:

Accumaltor recieves usage (number_of_api_calls: 2) with the current timestamp as end time. There is a previous usage (number_of_api_calls: 1) reported in the last minute and the current accumulated document time windows are set as: [1, 1, 1, 1, 1] (s, m, h, D, M). The new usage will accumulate accross all time windows (except second) as its end time is right after (less than a minute) the last sent usage consumption. So the resulting accumulated document will look like this: [1, 3, 3, 3, 3].

Example 2:

Accumaltor recieves usage (number_of_api_calls: 2) with the current timestamp as end time. There is a previous usage (number_of_api_calls: 1) reported _**5 hours ago**_ and the current accumulated document time windows are set as: [1, 1, 1, 1, 1] (s, m, h, D, M). The new usage will accumulate to the day and month time windows but not with the minute and hours windows. So the resulting accumulated document will look like this: [1, 1, 1, 3, 3].

# Slack period

Abacus checks every usage consumption document date and if it is too old the document gets rejected. The period of time in the past for which usage documents are accepted is configurable and is called _**slack period**_. By default the slack period is configured to 10m (10 minutes). It can be set by setting the env variable SLACK.

The slack period has direct relation to the time windows. The time dimension for which the slack period is defined has multiple values for every accumulated metric. The number of accumulated values is the same as the slack period plus one (the current value). This way when a new usage is received and the consumption end date is in the past (but still not older than the slack period) it will not be accumulated in the current entry but to the corresponding entry inside the time window dimension.

Example:

Lets have a slack period configured for the last 3 days:

```bash
export SLACK = 3D
```
The time windows in the accumulator document (metric number_of_api_calls) will loook like this (s, m, h, D, M):
```json
[ [null], [null], [null], [null, null, null, null], [null] ]
```
Because the slack period is set to 3 days the resulting time window for the day accumulation will have 3 entries (current + 3 days).

Lets assume we have a consumption reported (number_of_api_calls: 1). The result will look like this:
```json
[ [null], [ { 'current': 1 } ], [ { 'current': 1 } ], [ { 'current': 1 } , null, null, null], [ { 'current': 1 } ] ]
```
The current day time window contais the value of 1.

If there is another usage reported (number_of_api_calls: 2) after 24 h (1 day) the resulting doc is update as follows:
```json
[ [null], [ { 'current': 2 } ], [ { 'current': 2 } ], [ { 'current': 2 } , { 'current': 1 }, null, null], [ { 'current': 3, 'current': 1 } ] ]
```
The minute and hour values equal the new usage as in the last 60 min there were no other usages. The day usage is also 2 as for the last 24 h we don't have other usages. However as we have a configured slack period of 3 days the value for the previous day is not lost but shifted in the array with one index. The month value accumulates the new value as they are both in the same timeframe.

Lets now receive another usage (number_of_api_calls: 3) but its end date is from the previous day. Than we get:
```json
[ [null], [ { 'current': 2 } ], [ { 'current': 2 } ], [ { 'current': 2 } , { 'current': 4, 'previous': 1 }, null, null], [ { 'current': 6, 'previous': 3 } ] ]
```
The new usage is not accumulated in the minute or hour time windows as it is old. It is not part of the current daily accumulation but must be accumulated to the value of the previous day. The accumulated value for the month is updated too.
