### ISSUE TITLE
Consider Yarn for dependency management

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry-incubator/cf-abacus#771]
Seems like Yarn provides better management for fixing dependencies versions and integrity checks.

We should consider using it instead of shrinkwrap.

**Comment by iDaN5x** [comment]
Since version 5.0.0 `npm install` generates a `package-lock.json` file that is similar to `yarn.lock`.
Running `npm shrinkwrap` renames the file to `package-shrinkwrap.json`.
Both files include integrity check for each dependency.

Furthermore, since version 5.0.0 NPM is almost as fast as Yarn on all cases.
I believe it'll be better to just update to current version of NPM instead of switching to Yarn.

**Comment by hsiliev** [comment]
@iDaN5x We gave npm 5 a try but it is not a drop in replacement for npm 4. Seems it cannot resolve some of our dependencies. Not sure if this is npm issue or just the way we reference the dependencies.

With Yarn we want to:
* minimize and isolate dependencies in our internal modules
* have reproducible build (shrinkwrap)
* have consistency & integrity for modules (integrity checks in Yarn)
* speed up build/download times

Speed is not really the driving force here, but rather the rest of the list. If we can achieve the same with npm 5 that would be fine.

I marked this as "open for contribution", so you can either try to run Abacus with npm 5 or see if yarn can be easily integrated. Both would be helpful :)

**Comment by iDaN5x** [comment]
@hsiliev currently those are the only packages that use a shrinkwrap.
```bash
$ find . -name npm-shrinkwrap.json

./lib/aggregation/accumulator/npm-shrinkwrap.json
./lib/aggregation/aggregator/npm-shrinkwrap.json
./lib/aggregation/reporting/npm-shrinkwrap.json
./lib/cf/applications/npm-shrinkwrap.json
./lib/cf/renewer/npm-shrinkwrap.json
./lib/cf/services/npm-shrinkwrap.json
./lib/metering/collector/npm-shrinkwrap.json
./lib/metering/meter/npm-shrinkwrap.json
./lib/plugins/account/npm-shrinkwrap.json
./lib/plugins/authserver/npm-shrinkwrap.json
./lib/plugins/eureka/npm-shrinkwrap.json
./lib/plugins/provisioning/npm-shrinkwrap.json
./lib/utils/pouchserver/npm-shrinkwrap.json
./npm-shrinkwrap.json
./tools/cfpack/src/test/npm-shrinkwrap.json
```

There are total 103 of packages in the project - should we generate a `package-lock.json` / `yarn.lock` file for each of them?

**Comment by hsiliev** [comment]
Our current approach is to lock only the applications we push to CF. Our smoke, integration and acceptance tests guarantee that we don't break the Abacus pipeline.

The validation of individual modules is done on build via unit & integration tests, but without locks. This seems to break us from time to time. We hoped to have locks for all modules with npm 5. 

Having a lock for all modules seems to be aligned with the general direction of the node/npm community. Any thought here?

**Comment by hsiliev** [comment]
To move to npm 5 we need to:
* remove update script that caused strange errors
* remove shrinkwrap files
* re-implement or remove cfpack (I personally prefer the later)

Therefore I created #821 to enable use of npm 5

**Comment by iDaN5x** [comment]
I actually had fiddled with this a bit. It appears that NPM 5 now uses symlinks for local dependencies instead of copying.
This proved to be a real issue because a few circular dependencies exist which prevent `npm install` from working correctly.
Moving to npm 5 will indeed require modifications to current project structure.
Yarn on the other works like a charm since it doesn't use symlinks and leverage caching and flat directory structure.

I generated yarn files for the entire project running just the following command:
```bash
find . -name 'package.json' -not -path '*node_modules*' -exec dirname \; | parallel --tmuxpane 'cd {} && yarn install'
```

I'll open a PR tomorrow when I get to it.

**Comment by iDaN5x** [comment]
Please beware that the above command puts a lot of load on the CPU, as it run all installs on parallel, one using each core. This should take a few good minutes

**Comment by hsiliev** [comment]
We now have yarn instead of npm, so I'll close this bug.
