### ISSUE TITLE
Marshalling issue with deployment-pipeline-vars file

### ISSUE THREAD

**Issue by findneville** [cloudfoundry-incubator/cf-abacus#876]
Going through the deploy pipeline of cf-abacus and it appears that the pipeline does not like line
https://github.com/cloudfoundry-incubator/cf-abacus/blob/master/etc/concourse/deploy-pipeline-vars.yml#L50

Errors out with 
> line 50: cannot unmarshal !!seq into string

Tried to convert into a map and it failed too with 
> line 50: cannot unmarshal !!map into string

I am using Concourse v3.8.0 ..

After chatting on the Slack channel and going through some the scripts, I was finally able to get it working with the following format so that I don't have to change anything in the actual shell scripts:

> db-service-instances: |
>       service-instance-name:plan-name

This is not ideal but this should be fixed to something more meaningful

**Comment by hsiliev** [comment]
We're moving away from db service instances and closer to 12-factor-app state. As part of this effort we removed support for service instances inside Abacus and now rely on DB URIs only. New pipeline supporting this should materialize with #1057 and since we removed the old one I'm closing this issue as well.

For completeness the issue reported here was worked around in #1025 with:

> db-service-instances: !!str db-collector:standard db-meter:standard db-accumulator:standard db-aggregator:standard db-bridge:standard db-plugins:standard db-session:standard
