### ISSUE TITLE
The 'period' function in abacus-partition module '^0.0.2-rc' returns different value than '^0.0.1-dev.3'

### ISSUE THREAD

**Issue by piotrprzybylski** [cloudfoundry-incubator/cf-abacus#94]
The value retuned from period function in '0.0.2-rc' is different than value returned from the function in  '^0.0.1-dev.3'. 
```
describe.only('Check partition function', () => {

  // Old
  const periodDev3 = (t) => {
    // Use one period per day in the UTC timezone
    const d = new Date(parseInt(t));
    const per = d.getUTCFullYear() * 10000 + (d.getUTCMonth() + 1) * 100 +
      d.getUTCDate();
    return per;
  };

// New

  const periodRc0 = (t) => {
    // Use one period per day in the UTC timezone, # of days since Jan 1, 1970
    const per = Math.floor(parseInt(t) / 86400000)
    return per;
  };

  it('Compare old and new partition', (done) => {
    const now = Date.now();
    console.log('... now: ', now);

    const oldP = periodDev3(now);
    console.log('>> dev.3: ', oldP);

    const newP = periodRc0(now);
    console.log('>> rc.0: ', newP);

    expect(newP).to.equal(oldP);
    done();
  });
});

```

Output:
```
  Check partition function
... now:  1445047719259
>> dev.3:  20151017
>> rc.0:  16725
```

**Comment by jsdelfino** [comment]
The new behavior is correct. The default period function now returns the number of days since Jan 1, 1970 instead of a YYYYMMDD value, as iterating through YYYYMMDD in a range query would cause the query to go through invalid months (e.g. month 99) and days (e.g. day 99). If you depend on the old behavior of the partition function, you can still replicate it as the partition module can also use a custom user-defined period function, but I wouldn't recommend it as, as I just described here, the old YYYYMMDD format was fundamentally broken...

**Comment by piotrprzybylski** [comment]
The dependency was a conversion from timestamp to YYYYMM format. It seems this is now split between period and forward functions and externalized.

**Comment by jsdelfino** [comment]
The (default) period function converts a time to a number of days since Jan 1, 1970, and the (default) forward function converts that day to a year/month YYYYMM. These are the new default implementations, but they're externalizable so you should still be able to use other period and forward functions if you need.

**Comment by jsdelfino** [comment]
Answered your question. Please reopen if a code change is needed. Thanks!
